window.TRANSLATIONS = {
  "zh-Hant": {
    "skip.main": "跳到主要內容",
    "nav.menu": "開啟選單",
    "nav.why": "Why Now",
    "nav.format": "流程",
    "nav.tracks": "賽道",
    "nav.rules": "規則",
    "nav.prizes": "獎項",
    "nav.partners": "夥伴",
    "nav.faq": "FAQ",
    "meta.title": "可信 AI 黑客松 2026｜Trustworthy AI Hackathon｜TABEI",
    "meta.description": "Trustworthy AI Hackathon｜可信 AI 黑客松，2026/08/29-08/31 於 N24 台北方舟舉行，聚焦 AI Agent 的身份、授權、行動邊界與追溯機制。",
    "og.title": "Trustworthy AI Hackathon｜可信 AI 黑客松",
    "hero.title": "可信 AI 黑客松",
    "hero.body": "當 AI Agent 開始代表人或組織執行任務，身份、授權、行動邊界與追溯機制必須被清楚設計。",
    "hero.date": "2026/08/29–31",
    "hero.venue": "N24 台北方舟",
    "hero.format": "兩天一夜黑客松＋第三日 Demo Day",
    "trust.panel.title": "技術棧自由，信任要求明確",
    "trust.principal": "Principal｜代表誰",
    "trust.goal.short": "Goal / Task｜任務與完成條件",
    "trust.authorization": "Authorization｜被授權做什麼",
    "trust.tool": "Tool / Action｜能呼叫什麼工具",
    "trust.policy": "Policy Gate｜高風險動作如何被擋",
    "trust.audit": "Audit Log｜如何追溯行動",
    "trust.expiry": "Expiry / Revocation｜何時失效撤銷",
    "trust.governance.short": "Governance Gap｜台灣落地治理缺口",
    "why.title": "為什麼是現在",
    "why.subtitle": "AI Agent 的信任缺口，不能只靠更好的回答品質解決。",
    "why.body": "當 AI Agent 開始代替人決定、查詢、下單、送件或簽署時，風險不再只是模型答錯，而是可能發生越權操作、個資外洩、責任不明、授權無法撤銷，或無法證明某個行動由誰授意。",
    "why.q1": "它代表誰？",
    "why.q2": "被授權做什麼？",
    "why.q3": "授權何時失效？",
    "why.q4": "哪些動作需人類確認？",
    "why.q5": "出事後如何追溯與問責？",
    "position.title": "活動定位",
    "position.body": "一場以可信 AI Agent 為核心的高密度 builder program。",
    "position.build.title": "兩天一夜實作",
    "position.build.body": "從入選隊伍進入現場開發，完成可運作原型與 Demo Day 中文簡報。",
    "position.teams.title": "共同競爭",
    "position.teams.body": "20 隊入選隊伍在同一活動框架下完成可信 AI Agent 原型與 Demo Day 中文簡報。",
    "position.memo.title": "治理缺口 memo",
    "position.memo.body": "治理缺口 memo 作為作品交付的一部分，詳細格式以正式簡章為準。",
    "position.poc.title": "週末實作到 POC",
    "position.poc.body": "把可信 Agent 原型、場景問題與潛在合作機會接到後續 POC 討論。",
    "format.title": "形式與規模／三日流程",
    "format.body": "公開頁面只呈現已確認的參賽規模與流程重點。",
    "stat.teams": "入選隊伍",
    "stat.members": "每隊人數",
    "stat.participants": "預計參賽者",
    "stat.tracks": "落地賽道",
    "stat.workshops": "賽前工作坊",
    "day1.title": "開幕與隊伍確認",
    "day1.body": "報到、題目與活動規則說明、隊伍及參賽方向確認。",
    "day2.title": "實作與交件",
    "day2.body": "Build sprint、mentor office hours、收尾與正式交件。",
    "day3.title": "成果簡報與頒獎",
    "day3.body": "中文成果簡報、評審、頒獎與完賽證明。",
    "tracks.title": "四大賽道",
    "tracks.body": "One backbone, four scenarios. 每個作品都需回應一個具體場景中的可信問題。每隊只能選擇一個賽道，不可跨賽道投件。",
    "track.pain": "場景痛點",
    "track.trust": "核心可信問題",
    "track.example": "示例 POC",
    "track.supply.title": "供應鏈與貿易金融",
    "track.supply.pain": "供應商資格、訂單融資、ESG／碳資料可信度。",
    "track.supply.trust": "Agent 是否代表採購人／法人？能否讀取供應商憑證、草擬訂單，但禁止自行付款？",
    "track.supply.example": "供應商資格 VC、訂單即融資證明、ESG／碳盤查選擇性揭露、採購 Agent 授權。",
    "track.ecommerce.title": "電商與第三方支付",
    "track.ecommerce.pain": "高頻代購、支付授權、反詐騙、資格驗證。",
    "track.ecommerce.trust": "Agent 是否僅能比價與建立付款意向？何時必須由本人確認？",
    "track.ecommerce.example": "Agent 代購授權、商家可信驗證、年齡／資格選擇性揭露、付款前 human approval。",
    "track.health.title": "醫療保險",
    "track.health.pain": "高敏感個資、理賠、同意與核保稽核。",
    "track.health.trust": "Agent 可以讀取哪些醫療資料？是否有有效 consent？送件前如何確認？",
    "track.health.example": "理賠資料可信交換、同意 VC、隱私保護下聯合分析、AI 核保 action log。",
    "track.gov.title": "政府服務",
    "track.gov.pain": "公部門憑證、跨部會、代辦與國際互認。",
    "track.gov.trust": "Agent 可以代填、代查或代送到何種程度？哪些動作需本人確認？",
    "track.gov.example": "公部門憑證升級 VC、Agent 代辦申請、資格驗證、跨境互認概念。",
    "foundation.title": "共同主軸「信任地基」",
    "foundation.body": "所有賽道都需處理 identity · authorization · verification · privacy · security · accountability。",
    "foundation.principal": "代表誰？Agent 代表哪一個人、團隊、法人或公部門單位。",
    "foundation.goal": "Agent 的具體任務與完成條件是什麼？是否不是一般問答 chatbot？",
    "foundation.authorization": "被授權做什麼？誰授權、允許做什麼、禁止做什麼。",
    "foundation.tool": "能呼叫什麼工具？每個工具需要哪些權限與邊界。",
    "foundation.policy": "高風險動作如何被擋？付款、送件、簽署或讀取敏感資料需明確把關。",
    "foundation.audit": "如何追溯行動？記錄 Agent 的行動、決策與授權依據。",
    "foundation.expiry": "何時失效或撤銷？授權過期或撤銷後，Agent 必須停止執行。",
    "foundation.governance": "以一頁 memo 說明台灣落地所需的法規、標準、責任或資料治理缺口。",
    "foundation.note": "單純 chatbot 包裝不足以拿高分。作品應展示 Agent 在明確信任限制下完成真實任務，且能被驗證、限制、追溯。",
    "rules.title": "參賽資格與規則",
    "rules.body": "公開版只顯示已確認摘要；細節以正式簡章為準。",
    "rules.audience": "參賽對象",
    "rules.a1": "學生、青年開發者、業界開發者。",
    "rules.a2": "AI／資料、資安、區塊鏈、產品、設計或專案管理人才。",
    "rules.a3": "供應鏈、支付、醫療保險、政府服務等領域參與者。",
    "rules.a4": "鼓勵跨專業組隊，但所有成員必須在同一完整隊伍內報名。",
    "rules.team": "隊伍與出席",
    "rules.t1": "每隊 3-5 人，每位參賽者限加入一隊。",
    "rules.delivery": "出席與交付",
    "rules.d1": "入選隊伍應參與必要說明、兩場工作坊、技術彩排及活動主要流程；實際最低出席要求以正式簡章為準。",
    "rules.d2": "Demo Day 至少需有隊伍成員進行中文簡報。",
    "rules.d3": "須完成原型、Demo、簡報、README 與治理／信任設計說明；確切交件格式以正式簡章為準。",
    "rules.safety": "安全與資料",
    "rules.s1": "僅使用具合法授權的模型、資料、工具及第三方服務。",
    "rules.s2": "真實醫療、金融、政府或其他敏感資料不得使用。",
    "rules.s3": "敏感場景應使用匿名、合成或測試資料。",
    "rules.s4": "智慧財產權、影像授權、獎金稅務、夜間與未成年規範以正式簡章為準。",
    "judging.title": "評分資訊",
    "judging.body": "初選依題目相關性、可行性及團隊能力進行書面評估；候補機制以正式簡章為準。",
    "judging.prelim": "初選評估",
    "judging.relevance": "題目相關性",
    "judging.feasibility": "可行性",
    "judging.team": "團隊能力",
    "judging.final": "Demo Day 決選方式與完整評分標準，將於正式簡章公告。",
    "prize.title": "獎項",
    "prize.body": "現金獎金池 USD 12,000，持續加碼中。",
    "partners.title": "合作夥伴",
    "partners.body": "目前不顯示任何未正式確認的夥伴名稱或 Logo。",
    "partners.tech": "技術與生態系夥伴",
    "partners.community": "社群與人才夥伴",
    "partners.domain": "場景與領域夥伴",
    "partners.pending": "洽談中，將於正式確認後公布。",
    "partners.note": "合作單位、贊助商、講師與評審名單以正式公告為準。",
    "workshops.title": "賽前工作坊",
    "workshops.body": "共兩場，日期為 8/15、8/22，限入選隊伍參與。詳細主題、講者、形式與技術彩排安排後續公告。",
    "workshops.card1.meta": "8/15（六）",
    "workshops.card1.title": "Workshop #1",
    "workshops.card1.body": "限入選隊伍，不開放旁聽。詳細主題、講者與形式後續公告。",
    "workshops.card2.meta": "8/22（六）",
    "workshops.card2.title": "Workshop #2",
    "workshops.card2.body": "限入選隊伍，不開放旁聽。技術彩排與行前安排後續公告。",
    "roadmap.title": "時間軸",
    "roadmap.body": "已確認公開時程；工作坊限入選隊伍，不開放旁聽。",
    "date.info": "7/20（一）",
    "timeline.info": "線上說明會（線上）",
    "date.deadline": "8/5（三）",
    "timeline.deadline": "截止報名",
    "date.finalists": "8/7（五）",
    "timeline.finalists": "公告初選名單",
    "date.workshop1": "8/15（六）",
    "timeline.workshop1": "Workshop #1（限入選，不開放旁聽）",
    "date.workshop2": "8/22（六）",
    "timeline.workshop2": "Workshop #2（限入選，不開放旁聽）",
    "date.hackathon1": "8/29（六）",
    "timeline.hackathon1": "Hackathon Day 1（過夜）",
    "date.hackathon2": "8/30（日）",
    "timeline.hackathon2": "Hackathon Day 2",
    "date.demo": "8/31（一）",
    "timeline.demo": "Demo Day",
    "faq.title": "常見問答",
    "faq.body": "報名前可先確認資格、交付與規則。",
    "contact.title": "報名／聯絡",
    "contact.body": "報名由 Team Lead 代表完整隊伍提交；如有問題請聯絡臺灣區塊鏈愛好者協會。",
    "contact.name": "聯絡窗口",
    "contact.person": "臺灣區塊鏈愛好者協會",
    "contact.email": "聯絡臺灣區塊鏈愛好者協會｜contact@chain.tw",
    "contact.website": "回 chain.tw 主站",
    "footer.newsletter": "訂閱協會電子報",
    "footer.follow": "追蹤臺灣區塊鏈愛好者協會",
    "footer.website": "回到 chain.tw",
    "footer.org.zh": "臺灣區塊鏈愛好者協會",
    "footer.org.en": "Taiwan Association for Blockchain Ecosystem Innovation (TABEI)"
  },
  en: {
    "skip.main": "Skip to main content",
    "nav.menu": "Open menu",
    "nav.why": "Why Now",
    "nav.format": "Format",
    "nav.tracks": "Tracks",
    "nav.rules": "Rules",
    "nav.prizes": "Prize",
    "nav.partners": "Partners",
    "nav.faq": "FAQ",
    "meta.title": "Trustworthy AI Hackathon 2026｜TABEI",
    "meta.description": "Trustworthy AI Hackathon, 2026/08/29-08/31 at N24 Taipei Ark, focused on identity, authorization, action boundaries and traceability for AI Agents.",
    "og.title": "Trustworthy AI Hackathon",
    "hero.title": "Trustworthy AI Hackathon",
    "hero.body": "When AI Agents start acting for people or organizations, identity, authorization, action boundaries and traceability must be designed clearly.",
    "hero.date": "2026/08/29–31",
    "hero.venue": "N24 Taipei Ark",
    "hero.format": "2-day / 1-night hackathon + Demo Day",
    "trust.panel.title": "Stack freedom, clear trust requirements",
    "trust.principal": "Principal | who is represented",
    "trust.goal.short": "Goal / Task | task and completion criteria",
    "trust.authorization": "Authorization | what is allowed",
    "trust.tool": "Tool / Action | what tools can be called",
    "trust.policy": "Policy Gate | how high-risk actions are blocked",
    "trust.audit": "Audit Log | how actions are traceable",
    "trust.expiry": "Expiry / Revocation | when it expires or is revoked",
    "trust.governance.short": "Governance Gap | Taiwan deployment gaps",
    "why.title": "Why Now",
    "why.subtitle": "The trust gap around AI Agents cannot be solved only by better answers.",
    "why.body": "When AI Agents start deciding, querying, ordering, filing or signing on behalf of people, the risk is no longer just an incorrect answer. The real risks include unauthorized actions, personal-data leakage, unclear responsibility, non-revocable authorization and the inability to prove who instructed a given action.",
    "why.q1": "Who does it represent?",
    "why.q2": "What is it authorized to do?",
    "why.q3": "When does authorization expire?",
    "why.q4": "Which actions require human approval?",
    "why.q5": "How can incidents be traced and accounted for?",
    "position.title": "What It Is",
    "position.body": "A focused builder program centered on trustworthy AI Agents.",
    "position.build.title": "2-day / 1-night build",
    "position.build.body": "Selected teams build on site and deliver a working prototype plus a Chinese Demo Day presentation.",
    "position.teams.title": "Shared competition",
    "position.teams.body": "The 20 finalist teams build trustworthy AI Agent prototypes and Chinese Demo Day presentations under the same event framework.",
    "position.memo.title": "Governance gap memo",
    "position.memo.body": "The governance gap memo is part of the project deliverables; exact format is subject to the official rules.",
    "position.poc.title": "Weekend build toward POC",
    "position.poc.body": "Connect trustworthy Agent prototypes, scenario problems and potential collaboration opportunities to follow-on POC discussions.",
    "format.title": "Format, Scale & Three-day Flow",
    "format.body": "The public page shows only confirmed participant scale and flow highlights.",
    "stat.teams": "selected teams",
    "stat.members": "members per team",
    "stat.participants": "expected participants",
    "stat.tracks": "tracks",
    "stat.workshops": "workshops",
    "day1.title": "Kickoff and team confirmation",
    "day1.body": "Check-in, challenge and rules briefing, plus team and direction confirmation.",
    "day2.title": "Build and submit",
    "day2.body": "Build sprint, mentor office hours, finalization and formal submission.",
    "day3.title": "Demos and awards",
    "day3.body": "Chinese demos, judging, awards and completion proof.",
    "tracks.title": "Four Tracks",
    "tracks.body": "One backbone, four scenarios. Every project must address one concrete trust problem in context. Each team may choose only one track and may not submit across tracks.",
    "track.pain": "Scenario pain point",
    "track.trust": "Core trust question",
    "track.example": "Example POC",
    "track.supply.title": "Supply Chain & Trade Finance",
    "track.supply.pain": "Supplier qualification, order financing, and ESG / carbon-data trustworthiness.",
    "track.supply.trust": "Does the Agent represent the buyer or legal entity? Can it read supplier credentials and draft orders while being blocked from making payments on its own?",
    "track.supply.example": "Supplier qualification VC, order-to-financing proof, ESG / carbon selective disclosure, and procurement Agent authorization.",
    "track.ecommerce.title": "E-commerce & Third-Party Payments",
    "track.ecommerce.pain": "High-frequency delegated purchasing, payment authorization, fraud prevention, and eligibility verification.",
    "track.ecommerce.trust": "Can the Agent only compare prices and create payment intent? When must the user confirm?",
    "track.ecommerce.example": "Agent purchasing authorization, merchant trust verification, age / eligibility selective disclosure, and human approval before payment.",
    "track.health.title": "Health & Insurance",
    "track.health.pain": "Highly sensitive personal data, claims, consent, and underwriting audit.",
    "track.health.trust": "Which medical data can the Agent read? Is there valid consent? How is filing confirmed before submission?",
    "track.health.example": "Trusted claims data exchange, consent VC, privacy-preserving federated analysis, and AI underwriting action log.",
    "track.gov.title": "Government Services",
    "track.gov.pain": "Public-sector credentials, cross-agency processes, delegated filing, and international recognition.",
    "track.gov.trust": "How far can an Agent fill, query, or submit on someone's behalf? Which actions require personal confirmation?",
    "track.gov.example": "Public-sector credential upgrade VC, Agent-assisted applications, eligibility verification, and cross-border recognition concepts.",
    "foundation.title": "Trust Foundation",
    "foundation.body": "Every track must address identity · authorization · verification · privacy · security · accountability.",
    "foundation.principal": "Who is represented? Which person, team, legal entity or public-sector unit does the Agent represent?",
    "foundation.goal": "What is the Agent's concrete task and completion criteria? Is it more than a general Q&A chatbot?",
    "foundation.authorization": "What is authorized? Who authorizes it, what is allowed and what is forbidden?",
    "foundation.tool": "What tools can it call? What permissions and boundaries does each tool require?",
    "foundation.policy": "How are high-risk actions blocked? Payments, filing, signing or reading sensitive data require explicit gates.",
    "foundation.audit": "How are actions traced? Record the Agent's actions, decisions and authorization basis.",
    "foundation.expiry": "When does it expire or get revoked? After expiry or revocation, the Agent must stop executing.",
    "foundation.governance": "Use a one-page memo to explain regulatory, standards, responsibility or data-governance gaps for deployment in Taiwan.",
    "foundation.note": "A simple chatbot wrapper is not enough for a high score. Projects should show an Agent completing a real task under explicit trust constraints, with verification, limitation and traceability.",
    "rules.title": "Eligibility & Rules",
    "rules.body": "The public version shows only confirmed summaries; details are subject to the official rules.",
    "rules.audience": "Who can participate",
    "rules.a1": "Students, young developers and industry developers.",
    "rules.a2": "AI / data, security, blockchain, product, design or project-management talent.",
    "rules.a3": "Participants from supply chain, payments, health insurance and government services.",
    "rules.a4": "Cross-disciplinary teams are encouraged, but all members must register within one complete team.",
    "rules.team": "Team and attendance",
    "rules.t1": "Each team has 3-5 members, and each participant may join only one team.",
    "rules.delivery": "Attendance and deliverables",
    "rules.d1": "Selected teams should attend required briefings, two workshops, technical rehearsal and the main event flow; minimum attendance requirements are subject to the official rules.",
    "rules.d2": "At least one team member must give the Chinese Demo Day presentation.",
    "rules.d3": "Teams must complete a prototype, demo, slide deck, README and governance / trust design note; exact formats are subject to the official rules.",
    "rules.safety": "Safety and data",
    "rules.s1": "Use only legally authorized models, data, tools and third-party services.",
    "rules.s2": "Do not use real medical, financial, government or other sensitive data.",
    "rules.s3": "Sensitive scenarios should use anonymized, synthetic or test data.",
    "rules.s4": "IP, media consent, prize tax, overnight and minor-participant rules are subject to the official rules.",
    "judging.title": "Judging Information",
    "judging.body": "Preliminary review is based on relevance, feasibility and team capability; waitlist details are subject to the official rules.",
    "judging.prelim": "Preliminary review",
    "judging.relevance": "Relevance",
    "judging.feasibility": "Feasibility",
    "judging.team": "Team capability",
    "judging.final": "Demo Day final judging and full scoring criteria will be announced in the official rules.",
    "prize.title": "Prize",
    "prize.body": "Cash prize pool: USD 12,000, with more being added.",
    "partners.title": "Partners",
    "partners.body": "No unconfirmed partner names or logos are shown at this time.",
    "partners.tech": "Technology and ecosystem partners",
    "partners.community": "Community and talent partners",
    "partners.domain": "Scenario and domain partners",
    "partners.pending": "In discussion; to be announced after formal confirmation.",
    "partners.note": "Partners, sponsors, speakers and judges are subject to official announcement.",
    "workshops.title": "Pre-event Workshops",
    "workshops.body": "Two workshops are scheduled on 8/15 and 8/22 for selected teams only. Detailed topics, speakers, format and technical rehearsal arrangements will be announced later.",
    "workshops.card1.meta": "Aug 15 (Sat)",
    "workshops.card1.title": "Workshop #1",
    "workshops.card1.body": "For selected teams only; no auditing. Detailed topics, speakers and format will be announced later.",
    "workshops.card2.meta": "Aug 22 (Sat)",
    "workshops.card2.title": "Workshop #2",
    "workshops.card2.body": "For selected teams only; no auditing. Technical rehearsal and pre-event logistics will be announced later.",
    "roadmap.title": "Roadmap",
    "roadmap.body": "Confirmed public timeline; workshops are for selected teams only, with no auditing.",
    "date.info": "Jul 20 (Mon)",
    "timeline.info": "Online info session (online)",
    "date.deadline": "Aug 5 (Wed)",
    "timeline.deadline": "Registration deadline",
    "date.finalists": "Aug 7 (Fri)",
    "timeline.finalists": "Finalists announced",
    "date.workshop1": "Aug 15 (Sat)",
    "timeline.workshop1": "Workshop #1 (finalists only; no auditing)",
    "date.workshop2": "Aug 22 (Sat)",
    "timeline.workshop2": "Workshop #2 (finalists only; no auditing)",
    "date.hackathon1": "Aug 29 (Sat)",
    "timeline.hackathon1": "Hackathon Day 1 (overnight)",
    "date.hackathon2": "Aug 30 (Sun)",
    "timeline.hackathon2": "Hackathon Day 2",
    "date.demo": "Aug 31 (Mon)",
    "timeline.demo": "Demo Day",
    "faq.title": "FAQ",
    "faq.body": "Confirm eligibility, deliverables and rules before registration.",
    "contact.title": "Registration & Contact",
    "contact.body": "The Team Lead submits registration on behalf of the complete team. Contact Taiwan Association for Blockchain Ecosystem Innovation with questions.",
    "contact.name": "Contact",
    "contact.person": "Taiwan Association for Blockchain Ecosystem Innovation",
    "contact.email": "Contact Taiwan Association for Blockchain Ecosystem Innovation | contact@chain.tw",
    "contact.website": "Back to chain.tw",
    "footer.newsletter": "Subscribe to TABEI newsletter",
    "footer.follow": "Follow TABEI",
    "footer.website": "Back to chain.tw",
    "footer.org.zh": "Taiwan Association for Blockchain Ecosystem Innovation",
    "footer.org.en": "Taiwan Association for Blockchain Ecosystem Innovation (TABEI)"
  }
};

window.FAQ_GROUPS = {
  "zh-Hant": [
    ["A. 報名與隊伍", [
      ["每隊幾人？", "每隊 3-5 人，由 Team Lead 代表完整隊伍提交報名。"],
      ["是否接受個人報名或主辦方媒合？", "目前只接受完整隊伍報名，不提供個人報名或主辦方組隊媒合。"],
      ["每位參賽者可以加入多隊嗎？", "不可以，每位參賽者限加入一隊。"],
      ["可以跨賽道嗎？", "不可以。每隊只能選擇一個賽道，同一作品不得跨賽道投件或同時參與多個賽道評審。"],
      ["報名何時開放？", "2026 年 7 月 4 日開放，報名截止時間為 2026 年 8 月 5 日；最新時間以官方公告為準。"]
    ]],
    ["B. 初選與作品", [
      ["初選如何評分？是否有候補機制？", "初選依題目相關性 50%、可行性 30%、團隊能力 20% 評分；候補機制以正式簡章為準。"],
      ["什麼才算可信 AI Agent？一般 chatbot 可以嗎？", "作品需展示 Agent 代表誰、被授權做什麼、能呼叫什麼工具、如何被 policy gate 限制、如何追溯與撤銷；單純 chatbot wrapper 不足以拿高分。"],
      ["可以使用哪些模型、程式語言與 Agent framework？", "技術棧自由，可使用任一模型、程式語言、Agent framework、雲端或本地端環境。"],
      ["是否一定要使用 VC、DID、KERI、vLEI 或政府數位憑證皮夾？", "不強制。這些都是可選技術或加分方向，不是所有隊伍的硬性技術棧。"],
      ["可以使用既有程式碼與開源套件嗎？", "可以，但需揭露並遵守其授權條款。"],
      ["可以使用真實醫療、金融或政府資料嗎？", "不可以。敏感資料應使用匿名、合成或測試資料。"],
      ["哪些高風險動作需 human approval？", "付款、送件、簽署、讀取敏感資料或造成法律／業務效果的動作，應設計 human approval 或阻擋機制。"]
    ]],
    ["C. 工作坊與獎項", [
      ["兩場工作坊是否必須參加？", "入選隊伍應參與必要說明、兩場工作坊與技術彩排；實際要求以正式簡章為準。"],
      ["獎金如何安排？", "現金獎金池 USD 12,000，持續加碼中。"]
    ]],
    ["D. 法務、場務與聯絡", [
      ["智慧財產權、影像授權與獎金稅務如何處理？", "正式簡章另行公告，本頁不自行創造或擴張法律條款。"],
      ["活動地點與日期？", "2026/08/29–8/30 為 Hackathon，2026/08/31 為 Demo Day；地點為 N24 台北方舟。"],
      ["需要自行攜帶哪些設備？", "請自備開發所需筆電與周邊；其他現場設備需求以行前通知為準。"],
      ["夜間活動、餐飲、網路與休息安排何時公告？", "以正式簡章與入選後行前通知為準。"],
      ["有其他問題如何聯絡？", "請聯絡臺灣區塊鏈愛好者協會｜contact@chain.tw。"]
    ]]
  ],
  en: [
    ["A. Registration and Teams", [
      ["How many members per team?", "Each team has 3-5 members, and the Team Lead submits registration on behalf of the complete team."],
      ["Do you accept individual registration or organizer matching?", "At this stage, complete teams only. Individual registration and organizer-led team matching are not provided."],
      ["Can one participant join multiple teams?", "No. Each participant may join only one team."],
      ["Can we work across tracks?", "No. Each team may choose only one track. The same project may not be submitted across tracks or judged under multiple tracks."],
      ["When does registration open?", "Registration opens on July 4, 2026 and closes on August 5, 2026. Latest timing is subject to official announcement."]
    ]],
    ["B. Screening and Projects", [
      ["How does preliminary screening work? Is there a waitlist?", "Preliminary screening uses relevance 50%, feasibility 30% and team capability 20%. Waitlist details are subject to the official rules."],
      ["What counts as a trustworthy AI Agent? Is a chatbot enough?", "Projects must show who the Agent represents, what it is authorized to do, which tools it can call, how policy gates restrict actions, and how actions can be audited and authorization revoked. A simple chatbot wrapper is not enough for a high score."],
      ["What models, languages and Agent frameworks are allowed?", "Technology stack is open. Teams may use any model, programming language, Agent framework, cloud or local runtime."],
      ["Are VC, DID, KERI, vLEI or government digital wallets mandatory?", "No. These are optional technologies or bonus directions, not mandatory for every team."],
      ["Can teams use existing code or open-source packages?", "Yes, but teams must disclose usage and comply with the relevant licenses."],
      ["Can teams use real medical, financial or government data?", "No. Sensitive data should be replaced with anonymized, synthetic or test data."],
      ["Which high-risk actions require human approval?", "Payments, filing, signing, reading sensitive data, or actions with legal / business effect should include human approval or blocking mechanisms."]
    ]],
    ["C. Workshops and Prize", [
      ["Are the two workshops mandatory?", "Selected teams should attend required briefings, the two workshops and technical rehearsal. Actual requirements are subject to the official rules."],
      ["How is the cash prize arranged?", "Cash prize pool: USD 12,000, with more being added."]
    ]],
    ["D. Legal, Logistics and Contact", [
      ["How will IP, media consent and prize tax be handled?", "The official rules will announce details. This page does not create or expand legal terms."],
      ["When and where is the event?", "Hackathon is 2026/08/29–8/30, Demo Day is 2026/08/31, and the venue is N24 Taipei Ark."],
      ["What equipment should participants bring?", "Bring your development laptop and required peripherals. Other on-site requirements will be announced before the event."],
      ["When will overnight, meal, network and rest arrangements be announced?", "They will be announced in the official rules and selected-team briefing."],
      ["Who can I contact for other questions?", "Contact Taiwan Association for Blockchain Ecosystem Innovation | contact@chain.tw."]
    ]]
  ]
};
