window.TRANSLATIONS = {
  "zh-Hant": {
    "auto.1": "跳到主要內容",
    "auto.2": "開啟選單",
    "auto.3": "Why Now",
    "auto.4": "流程",
    "auto.5": "賽道",
    "auto.6": "規則",
    "auto.7": "獎項",
    "auto.8": "夥伴",
    "auto.9": "FAQ",
    "auto.10": "報名 Coming Soon",
    "auto.11": "可信 AI 黑客松",
    "auto.12": "當 AI Agent 開始代表人或組織執行任務，身份、授權、行動邊界與追溯機制必須被清楚設計。",
    "auto.13": "N24 台北方舟",
    "auto.14": "兩天一夜黑客松＋第三日 Demo Day",
    "auto.15": "報名即將開放 / Stay Tuned",
    "auto.16": "技術棧自由，信任要求明確",
    "auto.17": "Principal 代表誰",
    "auto.18": "Authorization 被授權做什麼",
    "auto.19": "Tool / Action 能呼叫什麼工具",
    "auto.20": "Policy Gate 高風險動作如何被擋",
    "auto.21": "Audit Log 如何追溯行動",
    "auto.22": "Expiry / Revocation 何時失效撤銷",
    "auto.23": "為什麼是現在",
    "auto.24": "AI Agent 的信任缺口，不能只靠更好的回答品質解決。",
    "auto.25": "當 AI Agent 開始代替人決定、查詢、下單、送件或簽署時，風險不再只是模型答錯，而是可能發生越權操作、個資外洩、責任不明、授權無法撤銷，或無法證明某個行動由誰授意。",
    "auto.26": "它代表誰？",
    "auto.27": "被授權做什麼？",
    "auto.28": "授權何時失效？",
    "auto.29": "哪些動作需人類確認？",
    "auto.30": "出事後如何追溯與問責？",
    "auto.31": "活動定位",
    "auto.32": "一場以可信 AI Agent 為核心的高密度 builder program。",
    "auto.33": "兩天一夜實作",
    "auto.34": "從入選隊伍進入現場開發，完成可運作原型與 Demo Day 中文簡報。",
    "auto.35": "20 隊混合組隊",
    "auto.36": "學生、業界開發者與領域專家共同實作，兼顧技術能力與場景理解。",
    "auto.37": "治理缺口 memo",
    "auto.38": "每隊交付一頁台灣落地治理缺口 memo，成為後續白皮書素材。",
    "auto.39": "週末實作到 POC",
    "auto.40": "把可信 Agent 原型、場景問題與合作管線接到後續 POC 討論。",
    "auto.41": "形式與規模／三日流程",
    "auto.42": "公開頁面只呈現參賽者需要知道的流程重點。",
    "auto.43": "入選隊伍",
    "auto.44": "每隊人數",
    "auto.45": "預計參賽者",
    "auto.46": "落地賽道",
    "auto.47": "賽前工作坊",
    "auto.48": "主獎得主",
    "auto.49": "開幕與組隊確認",
    "auto.50": "報到、夥伴出題、活動規則說明與組隊確認。",
    "auto.51": "實作與交件",
    "auto.52": "Build sprint、mentor office hours、收尾與正式交件。",
    "auto.53": "成果簡報與頒獎",
    "auto.54": "中文成果簡報、評審、頒獎與完賽 VC。",
    "auto.55": "四大賽道",
    "auto.56": "One backbone, four scenarios. 每個作品都需回應具體場景中的可信問題。",
    "auto.57": "供應鏈與貿易金融",
    "auto.58": "場景痛點",
    "auto.59": "供應商資格、訂單融資、ESG／碳資料可信度。",
    "auto.60": "核心可信問題",
    "auto.61": "Agent 是否代表採購人／法人？能否讀取供應商憑證、草擬訂單，但禁止自行付款？",
    "auto.62": "示例 POC",
    "auto.63": "供應商資格 VC、訂單即融資證明、ESG／碳盤查選擇性揭露、採購 Agent 授權。",
    "auto.64": "電商與第三方支付",
    "auto.65": "場景痛點",
    "auto.66": "高頻代購、支付授權、反詐騙、資格驗證。",
    "auto.67": "核心可信問題",
    "auto.68": "Agent 是否僅能比價與建立付款意向？何時必須由本人確認？",
    "auto.69": "示例 POC",
    "auto.70": "Agent 代購授權、商家可信驗證、年齡／資格選擇性揭露、付款前 human approval。",
    "auto.71": "醫療保險",
    "auto.72": "場景痛點",
    "auto.73": "高敏感個資、理賠、同意與核保稽核。",
    "auto.74": "核心可信問題",
    "auto.75": "Agent 可以讀取哪些醫療資料？是否有有效 consent？送件前如何確認？",
    "auto.76": "示例 POC",
    "auto.77": "理賠資料可信交換、同意 VC、隱私保護下聯合分析、AI 核保 action log。",
    "auto.78": "政府服務",
    "auto.79": "場景痛點",
    "auto.80": "公部門憑證、跨部會、代辦與國際互認。",
    "auto.81": "核心可信問題",
    "auto.82": "Agent 可以代填、代查或代送到何種程度？哪些動作需本人確認？",
    "auto.83": "示例 POC",
    "auto.84": "公部門憑證升級 VC、Agent 代辦申請、資格驗證、跨境互認概念。",
    "auto.85": "共同主軸「信任地基」",
    "auto.86": "所有賽道都需處理 identity · authorization · verification · privacy · security · accountability。",
    "auto.87": "代表誰？Agent 代表哪一個人、團隊、法人或公部門單位。",
    "auto.88": "被授權做什麼？誰授權、允許做什麼、禁止做什麼。",
    "auto.89": "能呼叫什麼工具？每個工具需要哪些權限與邊界。",
    "auto.90": "高風險動作如何被擋？付款、送件、簽署或讀取敏感資料需明確把關。",
    "auto.91": "如何追溯行動？記錄 Agent 的行動、決策與授權依據。",
    "auto.92": "何時失效或撤銷？授權過期或撤銷後，Agent 必須停止執行。",
    "auto.93": "單純 chatbot 包裝不足以拿高分。作品應展示 Agent 在明確信任限制下完成真實任務，且能被驗證、限制、追溯。",
    "auto.94": "參賽資格與規則",
    "auto.95": "鼓勵跨校、跨公司、跨技術與領域組隊。",
    "auto.96": "參賽對象",
    "auto.97": "學生、青年開發者與業界開發者。",
    "auto.98": "AI／資料、資安、區塊鏈、產品、設計或專案管理人才。",
    "auto.99": "供應鏈、支付、醫療保險、政府服務等領域參與者。",
    "auto.100": "隊伍與出席",
    "auto.101": "每隊 2-5 人，每位參賽者限加入一隊。",
    "auto.102": "可個人報名，再由主辦方協助媒合。",
    "auto.103": "入選隊伍需完整參與 8/29-31 主要流程。",
    "auto.104": "交付與注意事項",
    "auto.105": "需完成 demo、中文簡報與一頁治理缺口 memo。",
    "auto.106": "僅使用具合法授權的模型、資料、工具與第三方服務。",
    "auto.107": "敏感資料以匿名、合成或測試資料替代，並遵守 sponsor 使用規範。",
    "auto.108": "評分標準",
    "auto.109": "初選重視題目相關性；決選聚焦信任設計、技術完成度與場景適配。",
    "auto.110": "初選評估",
    "auto.111": "題目相關性",
    "auto.112": "可行性",
    "auto.113": "團隊能力",
    "auto.114": "決選評估",
    "auto.115": "信任架構",
    "auto.116": "技術執行",
    "auto.117": "場景適配",
    "auto.118": "獎項與開發資源",
    "auto.119": "主現金獎、Builder Kit、四大賽道獎與選配特別獎。",
    "auto.120": "主現金獎池，分配給 6 隊主獎得主。",
    "auto.121": "冠軍 Grand Prize：1 x USD 5,000",
    "auto.122": "亞軍 Excellence Award：2 x USD 2,000",
    "auto.123": "季軍 Merit Award：3 x USD 1,000",
    "auto.124": "20 隊入選皆有",
    "auto.125": "含 OpenAI、Gemini、Claude Code 等開發資源，以隊伍為單位分段發放。",
    "auto.126": "四大賽道獎",
    "auto.127": "硬體以 Mac mini 為目標；以贊助到位為準 / subject to sponsor confirmation。",
    "auto.128": "選配特別獎",
    "auto.129": "DGX Spark 等列為選配特別獎；以贊助到位為準 / subject to sponsor confirmation。",
    "auto.130": "憑證體驗（VC）作為亮點",
    "auto.131": "用於活動流程，但不綁死參賽技術棧。",
    "auto.132": "入選 Finalist VC",
    "auto.133": "報到 Participant Badge",
    "auto.134": "隊伍 Team Membership",
    "auto.135": "交件 Submission Receipt",
    "auto.136": "完賽 Completion VC",
    "auto.137": "得獎 Award VC",
    "auto.138": "活動以可驗證憑證串接關鍵節點；KERI、vLEI 與政府錢包可作為鼓勵或進階場景，不是所有隊伍的硬性門檻。",
    "auto.139": "賽前工作坊",
    "auto.140": "協助入選隊伍建立共同語言與技術起點。",
    "auto.141": "VC／DID 與活動憑證流程",
    "auto.142": "理解入選、報到、交件、完賽與得獎證明如何串接活動流程。",
    "auto.143": "KERI／vLEI 與可信授權",
    "auto.144": "聚焦法人、組織角色、Agent 委派授權與可撤銷的信任流程。",
    "auto.145": "時間軸",
    "auto.146": "從框架對齊到 Hackathon＋Demo Day。",
    "auto.147": "6 月",
    "auto.148": "框架與夥伴對齊",
    "auto.149": "7 月初",
    "auto.150": "正式公告、開放報名",
    "auto.151": "7 月中",
    "auto.152": "說明會與組隊媒合",
    "auto.153": "7 月下旬",
    "auto.154": "初選與入選確認",
    "auto.155": "8 月",
    "auto.157": "8/29-31",
    "auto.158": "Hackathon＋Demo Day",
    "auto.159": "合作夥伴與生態系",
    "auto.160": "實際角色以正式邀請與合作確認為準 / Roles confirmed through formal invitation and partner alignment.",
    "auto.161": "技術夥伴 Technology Partners",
    "auto.162": "洽談中／擬邀 · In discussion",
    "auto.163": "洽談中／擬邀 · In discussion",
    "auto.164": "洽談中／擬邀 · In discussion",
    "auto.165": "開發社群 Developer Communities",
    "auto.166": "洽談中／擬邀 · In discussion",
    "auto.167": "洽談中／擬邀 · In discussion",
    "auto.168": "指導單位 Guidance",
    "auto.169": "洽談中／擬邀 · In discussion",
    "auto.170": "洽談中／擬邀 · In discussion",
    "auto.171": "成為夥伴／徵求贊助",
    "auto.172": "把品牌放在可信 AI Agent 生態系的根部。",
    "auto.173": "常見問答",
    "auto.174": "報名前可先確認資格、交付與規則。",
    "auto.175": "誰可以參加？",
    "auto.176": "學生、青年開發者、業界開發者、設計／產品人才，以及四大賽道相關領域參與者皆可報名。",
    "auto.177": "需要什麼背景？",
    "auto.178": "活動鼓勵跨領域組隊。隊伍可包含開發、AI／資料、資安、區塊鏈、產品、設計、專案管理或領域專家。",
    "auto.179": "可以個人報名嗎？",
    "auto.180": "可以。個人可先報名，再由主辦方協助媒合；最終隊伍需為 2-5 人。",
    "auto.181": "簡報語言是什麼？",
    "auto.182": "Demo Day 以中文簡報與現場成果展示為主，技術名稱、程式碼與專有名詞可使用英文。",
    "auto.183": "可以用哪些技術棧？",
    "auto.184": "程式語言、模型、Agent framework、wallet、DID method、雲端或本地端環境皆可自由選擇；信任成果必須能被展示。",
    "auto.185": "需要交什麼？",
    "auto.186": "需完成可運作 demo、中文簡報與一頁台灣落地治理缺口 memo，並展示 Agent workflow、授權模型、工具行動與 audit trail。",
    "auto.187": "智財與資料規則如何處理？",
    "auto.188": "作品若使用既有程式或開源套件，應揭露並符合授權。敏感資料一律以匿名、合成或測試資料替代。",
    "auto.189": "報名何時開放？",
    "auto.190": "報名即將開放。可在本頁留下 email 訂閱搶先通知。",
    "auto.191": "報名／聯絡",
    "auto.192": "報名即將開放 Coming Soon。",
    "auto.193": "聯絡窗口",
    "auto.194": "回 chain.tw 主站",
    "auto.195": "Trustworthy AI Hackathon｜可信 AI 黑客松",
    "auto.196": "此欄位為前端佔位，不會送出真實表單。",
    "meta.title": "可信 AI 黑客松 2026｜Trustworthy AI Hackathon｜TABEI",
    "meta.description": "Trustworthy AI Hackathon｜可信 AI 黑客松，2026/08/29-31 於 N24 台北方舟舉行，聚焦 AI Agent 的身份、授權、驗證、隱私、安全與問責。",
    "nav.about": "活動介紹",
    "nav.tracks": "賽道",
    "nav.rules": "規則",
    "nav.judging": "評分與獎項",
    "nav.roadmap": "時程",
    "nav.faq": "FAQ",
    "nav.register": "報名即將開放",
    "lang.zh": "中",
    "lang.en": "EN",
    "hero.kicker": "Trustworthy AI Hackathon",
    "hero.title": "可信 AI 黑客松",
    "hero.subtitle": "Building the trust layer for the AI-Agent economy",
    "hero.meta.date": "2026/08/29-31",
    "hero.meta.place": "N24 台北方舟",
    "hero.meta.format": "兩天一夜黑客松＋第三日 Demo Day",
    "hero.thesis": "技術棧自由，信任成果必須可驗證",
    "hero.body": "當 AI Agent 開始代表人或組織執行任務，身份、授權、工具行動、policy gate、audit trail、失效／撤銷與治理缺口必須被清楚展示。",
    "hero.cta": "報名即將開放",
    "hero.newsletter": "訂閱協會電子報",
    "why.kicker": "01｜Why Now",
    "why.title": "核心命題",
    "why.body": "AI Agent 開始代替人決定、查詢、下單、送件或簽署時，必須能回答：它代表誰？被授權做什麼？授權何時失效？哪些動作需人類確認？出事後如何追溯與問責？",
    "overview.kicker": "02｜Overview",
    "overview.title": "活動概覽與關鍵數字",
    "overview.teams": "入選隊伍",
    "overview.members": "每隊人數",
    "overview.people": "參賽人數",
    "overview.tracks": "落地賽道",
    "overview.workshops": "賽前工作坊",
    "overview.winners": "主獎得主",
    "flow.kicker": "03｜Three-day Flow",
    "flow.title": "三日流程",
    "flow.day1.title": "Day 1｜開幕與組隊確認",
    "flow.day1.body": "報到、夥伴出題、活動規則說明與組隊確認。",
    "flow.day2.title": "Day 2｜實作與交件",
    "flow.day2.body": "Build sprint、mentor office hours、收尾與正式交件。",
    "flow.day3.title": "Demo Day｜成果簡報與頒獎",
    "flow.day3.body": "中文成果簡報、評審、頒獎與完賽 VC。",
    "tracks.kicker": "04｜Tracks",
    "tracks.title": "四大賽道",
    "tracks.subtitle": "每個作品都需回應具體場景中的可信問題。",
    "trust.kicker": "05｜Minimum Requirements",
    "trust.title": "可信 AI Agent 最低要求",
    "trust.note": "單純 chatbot wrapper 不足以拿高分。作品應展示 Agent 在明確信任限制下完成真實任務，且能被驗證、限制、追溯。",
    "trust.goal.short": "Goal / Task 任務與完成條件",
    "trust.governance.short": "Governance Gap 台灣落地治理缺口",
    "trust.goal.body": "Agent 的具體任務與完成條件是什麼？是否不是一般問答 chatbot？",
    "trust.governance.body": "以一頁 memo 說明台灣落地所需的法規、標準、責任或資料治理缺口。",
    "rules.kicker": "06｜Eligibility & Rules",
    "rules.title": "參賽資格與規則",
    "rules.body": "鼓勵跨校、跨公司、跨技術與領域組隊。入選隊伍需完整參與 8/29-31 主要流程，並完成 demo、中文簡報與一頁治理缺口 memo。",
    "judging.kicker": "07｜Judging",
    "judging.title": "初選與決選評分",
    "prizes.kicker": "08｜Prizes & Resources",
    "prizes.title": "獎項與 Builder Resources",
    "vc.kicker": "09｜Credential Experience",
    "vc.title": "VC 活動體驗",
    "vc.body": "活動以可驗證憑證串接入選、報到、隊伍、交件、完賽與得獎節點；KERI、vLEI 與政府錢包可作為鼓勵或進階場景，不是所有隊伍的硬性門檻。",
    "workshops.kicker": "10｜Workshops",
    "workshops.title": "四場賽前工作坊＋技術彩排",
    "workshop.2.title": "AI Agent 基礎、tool calling 與最低可信作品要求",
    "workshop.2.body": "建立可展示的 Agent workflow、tool action、授權模型與交件基準。",
    "workshop.3.title": "KERI／vLEI、法人角色與委派授權",
    "workshop.3.body": "聚焦法人、組織角色、Agent 委派授權與可撤銷的信任流程。",
    "workshop.4.title": "Agent Security、隱私與 red teaming",
    "workshop.4.body": "聚焦 prompt injection、tool misuse、privilege abuse 與資料外洩防護。",
    "roadmap.kicker": "11｜Roadmap",
    "roadmap.title": "籌備時間軸",
    "roadmap.workshops": "四場賽前工作坊與端到端技術彩排",
    "partners.kicker": "12｜Partners",
    "partners.title": "合作夥伴與贊助",
    "partners.note": "實際角色以正式邀請與合作確認為準 / Roles confirmed through formal invitation and partner alignment.",
    "sponsor.title": "成為夥伴",
    "sponsor.body": "Talent / Standards / Visibility / Pipeline：共同促成可被驗證、限制與追溯的可信 AI Agent 生態系。",
    "faq.kicker": "13｜FAQ",
    "faq.title": "完整參賽 FAQ",
    "contact.kicker": "14｜Registration & Contact",
    "contact.title": "報名／聯絡",
    "contact.body": "報名即將開放。若有合作、贊助或參賽問題，請聯絡 Taka。",
    "contact.email": "聯絡 Taka｜taka@chain.tw",
    "footer.follow": "追蹤臺灣區塊鏈愛好者協會",
    "footer.org.zh": "臺灣區塊鏈愛好者協會",
    "footer.org.en": "Taiwan Association for Blockchain Ecosystem Innovation (TABEI)",
    "footer.newsletter": "訂閱協會電子報",
    "footer.website": "回到 chain.tw",
  },
  en: {
    "auto.1": "Skip to main content",
    "auto.2": "Open menu",
    "auto.3": "Why Now",
    "auto.4": "Format",
    "auto.5": "Tracks",
    "auto.6": "Rules",
    "auto.7": "Prizes",
    "auto.8": "Partners",
    "auto.9": "FAQ",
    "auto.10": "Registration Coming Soon",
    "auto.11": "Trustworthy AI Hackathon",
    "auto.12": "When AI Agents start acting for people or organizations, identity, authorization, action boundaries and auditability must be designed clearly.",
    "auto.13": "N24 Taipei Ark",
    "auto.14": "2-day / 1-night hackathon + Demo Day",
    "auto.15": "Registration Coming Soon / Stay Tuned",
    "auto.16": "Stack freedom, clear trust requirements",
    "auto.17": "Principal: who is represented",
    "auto.18": "Authorization: what is allowed",
    "auto.19": "Tool / Action: what tools can be called",
    "auto.20": "Policy Gate: how high-risk actions are blocked",
    "auto.21": "Audit Log: how actions are traceable",
    "auto.22": "Expiry / Revocation: when it expires or is revoked",
    "auto.23": "Why Now",
    "auto.24": "The trust gap around AI Agents cannot be solved only by better answers.",
    "auto.25": "When AI Agents start deciding, querying, ordering, filing or signing on behalf of people, the risk is no longer just an incorrect answer. The real risks include unauthorized actions, personal-data leakage, unclear responsibility, non-revocable authorization and the inability to prove who instructed a given action.",
    "auto.26": "Who does it represent?",
    "auto.27": "What is it authorized to do?",
    "auto.28": "When does authorization expire?",
    "auto.29": "Which actions require human approval?",
    "auto.30": "How can incidents be traced and accounted for?",
    "auto.31": "What It Is",
    "auto.32": "A focused builder program centered on trustworthy AI Agents.",
    "auto.33": "2-day / 1-night build",
    "auto.34": "Selected teams build on site and deliver a working prototype plus a Chinese Demo Day presentation.",
    "auto.35": "20 mixed teams",
    "auto.36": "Students, industry developers and domain experts work together, balancing technical execution with scenario understanding.",
    "auto.37": "Governance gap memo",
    "auto.38": "Each team submits a one-page memo on Taiwan deployment governance gaps as input for white-paper work.",
    "auto.39": "Weekend build to POC",
    "auto.40": "Connect trustworthy Agent prototypes, scenario problems and partner pipelines to follow-on POC discussions.",
    "auto.41": "Format, Scale & Three-day Flow",
    "auto.42": "This public page presents the participant-facing flow only.",
    "auto.43": "selected teams",
    "auto.44": "people per team",
    "auto.45": "expected participants",
    "auto.46": "tracks",
    "auto.47": "pre-event workshops",
    "auto.48": "main prize winners",
    "auto.49": "Kickoff and team confirmation",
    "auto.50": "Check-in, partner challenges, rules briefing and team confirmation.",
    "auto.51": "Build and submit",
    "auto.52": "Build sprint, mentor office hours, finalization and formal submission.",
    "auto.53": "Demo and awards",
    "auto.54": "Chinese demos, judging, awards and Completion VC.",
    "auto.55": "Four Tracks",
    "auto.56": "One backbone, four scenarios. Every project should address a concrete trust problem in context.",
    "auto.57": "Supply Chain & Trade Finance",
    "auto.58": "Scenario pain point",
    "auto.59": "Supplier qualification, order financing and trustworthiness of ESG / carbon data.",
    "auto.60": "Core trust question",
    "auto.61": "Does the Agent represent a purchaser or legal entity? Can it read supplier credentials and draft orders while being blocked from making payments?",
    "auto.62": "Example POC",
    "auto.63": "Supplier qualification VC, order-as-financing proof, selective ESG / carbon disclosure and procurement Agent authorization.",
    "auto.64": "E-commerce & Third-party Payments",
    "auto.65": "Scenario pain point",
    "auto.66": "High-frequency purchasing, payment authorization, anti-fraud and eligibility verification.",
    "auto.67": "Core trust question",
    "auto.68": "Can the Agent only compare prices and create payment intent? When must the person confirm?",
    "auto.69": "Example POC",
    "auto.70": "Agent purchasing authorization, merchant trust verification, age / eligibility selective disclosure and human approval before payment.",
    "auto.71": "Health & Insurance",
    "auto.72": "Scenario pain point",
    "auto.73": "Highly sensitive personal data, claims, consent and underwriting audit.",
    "auto.74": "Core trust question",
    "auto.75": "Which medical data can the Agent read? Is there valid consent? How is filing confirmed before submission?",
    "auto.76": "Example POC",
    "auto.77": "Trusted claims data exchange, consent VC, privacy-preserving federated analysis and AI underwriting action log.",
    "auto.78": "Government Services",
    "auto.79": "Scenario pain point",
    "auto.80": "Public-sector credentials, cross-agency processes, delegated filing and international recognition.",
    "auto.81": "Core trust question",
    "auto.82": "How far can an Agent fill, query or submit on someone's behalf? Which actions require personal confirmation?",
    "auto.83": "Example POC",
    "auto.84": "Public-sector credential upgrade VC, Agent-assisted applications, eligibility verification and cross-border recognition concepts.",
    "auto.85": "Trust Foundation",
    "auto.86": "Every track must address identity · authorization · verification · privacy · security · accountability.",
    "auto.87": "Who is represented? Which person, team, legal entity or public-sector unit does the Agent represent?",
    "auto.88": "What is authorized? Who authorizes it, what is allowed and what is forbidden?",
    "auto.89": "What tools can it call? What permissions and boundaries does each tool require?",
    "auto.90": "How are high-risk actions blocked? Payments, filing, signing or reading sensitive data require explicit gates.",
    "auto.91": "How are actions traced? Record the Agent's actions, decisions and authorization basis.",
    "auto.92": "When does it expire or get revoked? After expiry or revocation, the Agent must stop executing.",
    "auto.93": "A simple chatbot wrapper is not enough for a high score. Projects should show an Agent completing a real task under explicit trust constraints, with verification, limitation and traceability.",
    "auto.94": "Eligibility & Rules",
    "auto.95": "Cross-school, cross-company, cross-technical and domain teams are encouraged.",
    "auto.96": "Who can participate",
    "auto.97": "Students, young developers and industry developers.",
    "auto.98": "AI / data, security, blockchain, product, design or project-management talent.",
    "auto.99": "Participants from supply chain, payments, health insurance and government services.",
    "auto.100": "Team and attendance",
    "auto.101": "Each team has 2-5 people. Each participant may join only one team.",
    "auto.102": "Individuals may register first and be matched by the organizer.",
    "auto.103": "Selected teams must participate in the main 8/29-31 program.",
    "auto.104": "Deliverables and notes",
    "auto.105": "Teams must complete a demo, a Chinese presentation and a one-page governance gap memo.",
    "auto.106": "Use only legally authorized models, data, tools and third-party services.",
    "auto.107": "Replace sensitive data with anonymized, synthetic or test data, and follow sponsor usage rules.",
    "auto.108": "Judging Criteria",
    "auto.109": "Initial screening prioritizes topic relevance; final judging focuses on trust architecture, technical execution and scenario fit.",
    "auto.110": "Initial screening",
    "auto.111": "Topic relevance",
    "auto.112": "Feasibility",
    "auto.113": "Team capability",
    "auto.114": "Final evaluation",
    "auto.115": "Trust architecture",
    "auto.116": "Technical execution",
    "auto.117": "Scenario fit",
    "auto.118": "Prizes & Builder Resources",
    "auto.119": "Main cash prizes, Builder Kits, Best Track Awards and optional special awards.",
    "auto.120": "Main cash prize pool for 6 winning teams.",
    "auto.121": "Grand Prize: 1 x USD 5,000",
    "auto.122": "Excellence Award: 2 x USD 2,000",
    "auto.123": "Merit Award: 3 x USD 1,000",
    "auto.124": "For all 20 selected teams",
    "auto.125": "Includes OpenAI, Gemini, Claude Code and other builder resources, released by team in stages.",
    "auto.126": "Best Track Awards",
    "auto.127": "Hardware target: Mac mini; subject to sponsor confirmation.",
    "auto.128": "Optional special award",
    "auto.129": "DGX Spark and similar items are optional special awards, subject to sponsor confirmation.",
    "auto.130": "Credential Experience as a Highlight",
    "auto.131": "Used for event operations, without locking teams into a required development stack.",
    "auto.132": "Selected Finalist VC",
    "auto.133": "Check-in Participant Badge",
    "auto.134": "Team Membership",
    "auto.135": "Submit Submission Receipt",
    "auto.136": "Complete Completion VC",
    "auto.137": "Award VC",
    "auto.138": "The event uses verifiable credentials to connect key milestones. KERI, vLEI and government wallets are encouraged or advanced scenarios, not mandatory requirements for all teams.",
    "auto.139": "Pre-event Workshops",
    "auto.140": "Helping selected teams build a shared vocabulary and technical starting point.",
    "auto.141": "VC / DID and event credential flow",
    "auto.142": "Understand how selected, check-in, submission, completion and award credentials connect to the event flow.",
    "auto.143": "KERI / vLEI and trustworthy authorization",
    "auto.144": "Focus on legal entities, organizational roles, Agent delegated authorization and revocable trust flows.",
    "auto.145": "Roadmap",
    "auto.146": "From framework alignment to Hackathon + Demo Day.",
    "auto.147": "June",
    "auto.148": "Framework and partner alignment",
    "auto.149": "Early July",
    "auto.150": "Public launch and registration opens",
    "auto.151": "Mid July",
    "auto.152": "Info session and team matching",
    "auto.153": "Late July",
    "auto.154": "Screening and selected-team confirmation",
    "auto.155": "August",
    "auto.157": "8/29-31",
    "auto.158": "Hackathon + Demo Day",
    "auto.159": "Partners & Ecosystem",
    "auto.160": "Roles confirmed through formal invitation and partner alignment.",
    "auto.161": "Technology Partners",
    "auto.162": "In discussion",
    "auto.163": "In discussion",
    "auto.164": "In discussion",
    "auto.165": "Developer Communities",
    "auto.166": "In discussion",
    "auto.167": "In discussion",
    "auto.168": "Guidance",
    "auto.169": "In discussion",
    "auto.170": "In discussion",
    "auto.171": "Become a Partner",
    "auto.172": "Put your brand at the root of the trustworthy AI Agent ecosystem.",
    "auto.173": "FAQ",
    "auto.174": "Confirm eligibility, deliverables and rules before registration opens.",
    "auto.175": "Who can participate?",
    "auto.176": "Students, young developers, industry developers, design / product talent and participants from the four track domains may register.",
    "auto.177": "What background do I need?",
    "auto.178": "Cross-disciplinary teams are encouraged. Teams may include development, AI / data, security, blockchain, product, design, project management or domain expertise.",
    "auto.179": "Can I register as an individual?",
    "auto.180": "Yes. Individuals may register first and be matched by the organizer. Final teams must have 2-5 people.",
    "auto.181": "What is the presentation language?",
    "auto.182": "Demo Day uses Chinese presentations and live demos. Technical names, code and terms may be in English.",
    "auto.183": "What technology stacks are allowed?",
    "auto.184": "Teams may choose any programming language, model, Agent framework, wallet, DID method, cloud or local environment. Trust outcomes must be demonstrable.",
    "auto.185": "What must teams submit?",
    "auto.186": "Teams must submit a working demo, Chinese presentation and one-page Taiwan governance gap memo, and show Agent workflow, authorization model, tool action and audit trail.",
    "auto.187": "How are IP and data rules handled?",
    "auto.188": "Existing code or open-source packages must be disclosed and comply with their licenses. Sensitive data must be replaced with anonymized, synthetic or test data.",
    "auto.189": "When will registration open?",
    "auto.190": "Registration is coming soon. Leave an email on this page for early updates.",
    "auto.191": "Registration & Contact",
    "auto.192": "Registration is coming soon.",
    "auto.193": "Contact",
    "auto.194": "Back to chain.tw",
    "auto.195": "Trustworthy AI Hackathon",
    "auto.196": "This is a front-end placeholder and does not submit a real form.",
    "meta.title": "Trustworthy AI Hackathon 2026｜TABEI",
    "meta.description": "Trustworthy AI Hackathon, 2026/08/29-31 at N24 Taipei Ark, focused on identity, authorization, verification, privacy, security and accountability for AI Agents.",
    "nav.about": "About",
    "nav.tracks": "Tracks",
    "nav.rules": "Rules",
    "nav.judging": "Judging & Prizes",
    "nav.roadmap": "Roadmap",
    "nav.faq": "FAQ",
    "nav.register": "Registration Coming Soon",
    "lang.zh": "中",
    "lang.en": "EN",
    "hero.kicker": "Trustworthy AI Hackathon",
    "hero.title": "Trustworthy AI Hackathon",
    "hero.subtitle": "Building the trust layer for the AI-Agent economy",
    "hero.meta.date": "2026/08/29-31",
    "hero.meta.place": "N24 Taipei Ark",
    "hero.meta.format": "2-day / 1-night hackathon + Demo Day",
    "hero.thesis": "Stack freedom. Trust outcomes must be verifiable.",
    "hero.body": "When AI Agents start acting for people or organizations, teams must demonstrate identity, authorization, tool action, policy gates, audit trails, expiry / revocation and governance gaps.",
    "hero.cta": "Registration Coming Soon",
    "hero.newsletter": "Subscribe to TABEI newsletter",
    "why.kicker": "01｜Why Now",
    "why.title": "The Core Question",
    "why.body": "When AI Agents start deciding, querying, ordering, filing or signing on behalf of people, they must answer: who do they represent, what are they authorized to do, when does authorization expire, which actions require human approval, and how can incidents be traced and accounted for?",
    "overview.kicker": "02｜Overview",
    "overview.title": "Overview and Key Numbers",
    "overview.teams": "selected teams",
    "overview.members": "people per team",
    "overview.people": "participants",
    "overview.tracks": "tracks",
    "overview.workshops": "workshops",
    "overview.winners": "main prize winners",
    "flow.kicker": "03｜Three-day Flow",
    "flow.title": "Three-day Flow",
    "flow.day1.title": "Day 1｜Kickoff and team confirmation",
    "flow.day1.body": "Check-in, partner challenges, rules briefing and team confirmation.",
    "flow.day2.title": "Day 2｜Build and submit",
    "flow.day2.body": "Build sprint, mentor office hours, finalization and formal submission.",
    "flow.day3.title": "Demo Day｜Demos and awards",
    "flow.day3.body": "Chinese demos, judging, awards and Completion VC.",
    "tracks.kicker": "04｜Tracks",
    "tracks.title": "Four Tracks",
    "tracks.subtitle": "Every project should address a concrete trust problem in context.",
    "trust.kicker": "05｜Minimum Requirements",
    "trust.title": "Minimum Trustworthy AI Agent Requirements",
    "trust.note": "A simple chatbot wrapper is not enough for a high score. Projects should show an Agent completing a real task under explicit trust constraints, with verification, limitation and traceability.",
    "trust.goal.short": "Goal / Task: task and completion criteria",
    "trust.governance.short": "Governance Gap: Taiwan deployment gaps",
    "trust.goal.body": "What is the Agent's concrete task and completion criteria? Is it more than a general Q&A chatbot?",
    "trust.governance.body": "Use a one-page memo to explain regulatory, standards, responsibility or data-governance gaps for deployment in Taiwan.",
    "rules.kicker": "06｜Eligibility & Rules",
    "rules.title": "Eligibility and Rules",
    "rules.body": "Cross-school, cross-company, cross-technical and domain teams are encouraged. Selected teams must participate in the main 8/29-31 program and complete a demo, Chinese presentation and one-page governance gap memo.",
    "judging.kicker": "07｜Judging",
    "judging.title": "Initial Screening and Final Evaluation",
    "prizes.kicker": "08｜Prizes & Resources",
    "prizes.title": "Prizes and Builder Resources",
    "vc.kicker": "09｜Credential Experience",
    "vc.title": "Credential Experience",
    "vc.body": "The event uses verifiable credentials to connect selected, check-in, team, submission, completion and award milestones. KERI, vLEI and government wallets are encouraged or advanced scenarios, not mandatory requirements for all teams.",
    "workshops.kicker": "10｜Workshops",
    "workshops.title": "Four Pre-event Workshops + Technical Rehearsal",
    "workshop.2.title": "AI Agent basics, tool calling and minimum trustworthy project requirements",
    "workshop.2.body": "Build demonstrable Agent workflows, tool actions, authorization models and submission baselines.",
    "workshop.3.title": "KERI / vLEI, legal-entity roles and delegated authorization",
    "workshop.3.body": "Focus on legal entities, organizational roles, Agent delegated authorization and revocable trust flows.",
    "workshop.4.title": "Agent Security, privacy and red teaming",
    "workshop.4.body": "Focus on prompt injection, tool misuse, privilege abuse and data-leakage defenses.",
    "roadmap.kicker": "11｜Roadmap",
    "roadmap.title": "Preparation Roadmap",
    "roadmap.workshops": "Four pre-event workshops and end-to-end technical rehearsal",
    "partners.kicker": "12｜Partners",
    "partners.title": "Partners and Sponsorship",
    "partners.note": "Roles confirmed through formal invitation and partner alignment.",
    "sponsor.title": "Become a Partner",
    "sponsor.body": "Talent / Standards / Visibility / Pipeline: help build an ecosystem for verifiable, limited and traceable trustworthy AI Agents.",
    "faq.kicker": "13｜FAQ",
    "faq.title": "Participant FAQ",
    "contact.kicker": "14｜Registration & Contact",
    "contact.title": "Registration and Contact",
    "contact.body": "Registration is coming soon. For partnership, sponsorship or participant questions, contact Taka.",
    "contact.email": "Contact Taka｜taka@chain.tw",
    "footer.follow": "Follow TABEI",
    "footer.org.zh": "Taiwan Association for Blockchain Ecosystem Innovation",
    "footer.org.en": "Taiwan Association for Blockchain Ecosystem Innovation (TABEI)",
    "footer.newsletter": "Subscribe to TABEI newsletter",
    "footer.website": "Back to chain.tw",
  },
};

window.FAQ_GROUPS = {
  "zh-Hant": [
    ["A. 報名與組隊", [
      ["誰可以參加？", "學生、青年開發者、業界開發者、設計／產品人才，以及供應鏈、支付、醫療保險、政府服務等四大賽道相關領域參與者皆可報名。"],
      ["需要具備哪些背景？", "不限定單一背景。建議隊伍具備開發、AI／資料、資安、產品、設計、專案管理或領域知識。"],
      ["可以個人報名嗎？如何媒合？", "可以。個人可先報名，主辦方將依技能、賽道與可投入時段協助媒合。"],
      ["每隊幾人？每位參賽者可否加入多隊？", "每隊 2–5 人；每位參賽者限加入一隊。"],
      ["可以跨校、跨公司或跨領域組隊嗎？", "可以，也鼓勵跨校、跨公司、跨技術與領域組隊。"],
      ["每隊是否只能選一個賽道？跨賽道作品如何評審？", "每隊需指定一個主賽道；跨賽道作品仍以主賽道作為主要評審場景。"],
      ["入選後是否必須全程出席？", "入選隊伍需完整參與 8/29–31 主要流程與 Demo Day。"],
      ["初選如何評分？是否有候補機制？", "初選依題目相關性 50%、可行性 30%、團隊能力 20% 評分；候補機制以正式簡章為準。"],
      ["報名何時開放？", "報名即將開放，正式時間以活動公告為準。"],
    ]],
    ["B. 開發與技術", [
      ["什麼才算可信 AI Agent？一般 chatbot 可以嗎？", "作品需展示 Agent 代表誰、被授權做什麼、能呼叫什麼工具、如何被 policy gate 限制、如何追溯與撤銷；單純 chatbot wrapper 不足以拿高分。"],
      ["可以使用哪些模型、程式語言與 Agent framework？", "技術棧自由，可使用任一模型、程式語言、Agent framework、雲端或本地端環境。"],
      ["是否一定要使用 VC、DID、KERI、vLEI 或政府數位憑證皮夾？", "不強制。這些都是可選技術或加分方向，不是所有隊伍的硬性技術棧。"],
      ["可以使用既有程式碼與開源套件嗎？", "可以，但需揭露並遵守其授權條款。"],
      ["可以使用真實醫療、金融或政府資料嗎？", "不可以。敏感資料應使用匿名、合成或測試資料。"],
      ["哪些高風險動作需 human approval？", "付款、送件、簽署、讀取敏感資料或造成法律／業務效果的動作，應設計 human approval 或阻擋機制。"],
    ]],
    ["C. 交件與評分", [
      ["必須提交哪些內容？", "至少包含可運作原型、現場 Demo、中文簡報、程式碼／技術文件與一頁台灣落地治理缺口 memo。"],
      ["Demo Day 使用什麼語言？", "Demo Day 以中文簡報與現場成果展示為主；技術名稱、程式碼、專有名詞可使用英文。"],
      ["初選 50/30/20 的評分方式為何？", "題目相關性 50%、可行性 30%、團隊能力 20%。"],
      ["決選 40/35/25 的評分方式為何？", "信任架構 40%、技術執行 35%、場景適配 25%。"],
      ["完賽與取得 Completion VC 的條件為何？", "需到場參與、完成交件、完成 Demo Day 展示；細節以正式簡章為準。"],
    ]],
    ["D. 資源與獎項", [
      ["Builder Kit / AI credits 如何提供？", "提供給 20 隊入選隊伍，以隊伍為單位並可分階段發放。"],
      ["四場工作坊是否必須參加？", "入選隊伍應參與必要說明、工作坊與技術彩排；實際要求以正式簡章為準。"],
      ["現金獎如何分配？", "主現金獎池 USD 12,000：冠軍 1 隊 x USD 5,000、亞軍 2 隊 x USD 2,000、季軍 3 隊 x USD 1,000。"],
      ["主獎與 Best Track Award 可以重疊嗎？", "可以；同一隊原則最多一個主現金獎加一個賽道獎，特別獎另計。"],
      ["Mac mini／DGX Spark 是否確定？", "Mac mini 為四大賽道獎目標硬體，DGX Spark 為 sponsor-backed 選配特別獎；皆以正式贊助公告為準。"],
    ]],
    ["E. 法務、場務與聯絡", [
      ["智慧財產權、影像授權、獎金稅務如何處理？", "正式簡章另行公告，不在本頁自行創造條款。"],
      ["活動地點與日期？", "2026/08/29–8/30 黑客松；2026/08/31 Demo Day。地點為 N24 台北方舟。"],
      ["需要自行攜帶哪些設備？", "請自備開發所需筆電與周邊；其他現場設備需求以行前通知為準。"],
      ["夜間活動、餐飲、網路與休息安排何時公告？", "以正式簡章與入選後行前通知為準。"],
      ["有其他問題如何聯絡？", "請聯絡 Taka｜taka@chain.tw。"],
    ]],
  ],
  en: [
    ["A. Registration and Teaming", [
      ["Who can participate?", "Students, young developers, industry developers, design / product talent and participants from the four track domains may register."],
      ["What background do I need?", "No single background is required. Teams should ideally include development, AI / data, security, product, design, project management or domain expertise."],
      ["Can I register as an individual?", "Yes. Individuals may register first, and the organizer will help match teams by skill, track and availability."],
      ["How many people per team? Can one person join multiple teams?", "Each team has 2–5 people. Each participant may join only one team."],
      ["Can teams cross schools, companies or domains?", "Yes. Cross-school, cross-company, cross-technical and domain teams are encouraged."],
      ["Can a team work across tracks?", "Each team must specify one main track. Cross-track projects will still be primarily judged under their selected main track."],
      ["Must selected teams attend the full event?", "Selected teams must participate in the main 8/29–31 program and Demo Day."],
      ["How does initial screening work?", "Initial screening uses topic relevance 50%, feasibility 30% and team capability 20%. Waitlist details are subject to the official rules."],
      ["When will registration open?", "Registration is coming soon. The official date will be announced on the event page."],
    ]],
    ["B. Development and Technology", [
      ["What counts as a trustworthy AI Agent?", "Teams must show who the Agent represents, what it is authorized to do, which tools it can call, how policy gates restrict actions, how actions are audited and how authorization expires or is revoked."],
      ["What models, languages and frameworks are allowed?", "The stack is free. Teams may use any model, language, Agent framework, cloud or local runtime."],
      ["Are VC, DID, KERI, vLEI or government wallets mandatory?", "No. They are optional technologies or bonus directions, not mandatory for every team."],
      ["Can teams use existing code or open-source packages?", "Yes, but teams must disclose usage and comply with the relevant licenses."],
      ["Can teams use real medical, financial or government data?", "No. Sensitive data should be replaced with anonymized, synthetic or test data."],
      ["Which high-risk actions require human approval?", "Payments, filing, signing, reading sensitive data or actions with legal / business effect should include human approval or blocking mechanisms."],
    ]],
    ["C. Submission and Judging", [
      ["What must teams submit?", "At minimum: working prototype, live demo, Chinese presentation, code / technical documentation and one-page Taiwan governance gap memo."],
      ["What language is used on Demo Day?", "Demo Day uses Chinese presentations and live demos. Technical names, code and terms may be in English."],
      ["How does 50/30/20 initial screening work?", "Topic relevance 50%, feasibility 30% and team capability 20%."],
      ["How does 40/35/25 final judging work?", "Trust architecture 40%, technical execution 35% and scenario fit 25%."],
      ["What qualifies for Completion VC?", "Teams must attend, submit required materials and present on Demo Day. Details are subject to the official rules."],
    ]],
    ["D. Resources and Prizes", [
      ["How are Builder Kits / AI credits provided?", "They are provided to the 20 selected teams by team and may be released in stages."],
      ["Are the four workshops mandatory?", "Selected teams should attend required briefings, workshops and technical rehearsal. Requirements are subject to official rules."],
      ["How are cash prizes distributed?", "Main cash prize pool: USD 12,000. Grand Prize: 1 x USD 5,000; Excellence: 2 x USD 2,000; Merit: 3 x USD 1,000."],
      ["Can main prizes and Best Track Awards overlap?", "Yes. One team should generally receive at most one main cash prize plus one track award; special awards are separate."],
      ["Are Mac mini / DGX Spark confirmed?", "Mac mini is the target hardware for Best Track Awards; DGX Spark is an optional sponsor-backed special award. Both are subject to official sponsor confirmation."],
    ]],
    ["E. Legal, Logistics and Contact", [
      ["How will IP, media consent and prize tax be handled?", "The official rulebook will announce details. This page does not create legal terms."],
      ["When and where is the event?", "Hackathon: 2026/08/29–8/30. Demo Day: 2026/08/31. Venue: N24 Taipei Ark."],
      ["What equipment should participants bring?", "Bring your development laptop and required peripherals. Other on-site requirements will be announced before the event."],
      ["When will overnight, meal, network and rest arrangements be announced?", "They will be announced in the official rules and selected-team briefing."],
      ["Who can I contact for other questions?", "Contact Taka｜taka@chain.tw."],
    ]],
  ],
};
