window.TRANSLATIONS = {
  "zh-Hant": {
    "skip.main": "跳到主要內容",
    "nav.menu": "開啟選單",
    "nav.close": "關閉選單",
    "aria.nav": "主選單",
    "aria.language": "語言切換",
    "aria.registrationFlow": "報名與組隊媒合流程",
    "aria.eventInfo": "活動資訊",
    "aria.eventNumbers": "活動數字",
    "aria.roles": "參與角色",
    "aria.timeline": "活動流程圖",
    "aria.eventScale": "活動規模",
    "aria.organizerVenue": "主辦與場地",
    "aria.mapTitle": "N24 台北方舟 Google 地圖",
    "nav.format": "流程",
    "nav.tracks": "產業命題",
    "nav.rules": "規則",
    "nav.prizes": "獎項",
    "nav.faq": "FAQ",
    "meta.title": "可信 AI 黑客松 2026｜Trustworthy AI Hackathon｜TABEI",
    "meta.description": "Trustworthy AI Hackathon｜可信 AI 黑客松，2026/08/29–08/31 於 N24 台北方舟舉行，聚焦可信 AI Agent 的身份、授權、行動邊界與可追溯性。",
    "og.title": "Trustworthy AI Hackathon｜可信 AI 黑客松",
    "hero.title": "可信 AI 黑客松",
    "solo.badge": "個人／未滿員隊伍皆可",
    "solo.title": "個人、未滿員隊伍，都可以先報名",
    "solo.body": "個人、未滿員或完整 3–5 人隊伍皆可先報名；入選後可在兩場賽前工作坊媒合，最終組成 3–5 人隊伍。",
    "solo.step1.title": "先送出報名",
    "solo.step1.body": "個人自行提交；隊伍由 Team Leader 代表提交。",
    "solo.step2.title": "認識與媒合隊友",
    "solo.step2.body": "可先使用媒合平台；入選後兩場工作坊皆可媒合。",
    "solo.step3.title": "確認 3–5 人隊伍",
    "solo.step3.body": "最終名單每隊 3–5 人，每位參賽者限加入一隊。",
    "hero.body": "當 AI Agent 開始代表人或組織行動，身份、授權、行動邊界與可追溯性必須被清楚設計。",
    "hero.date": "08.29-08.30 Hackathon｜08.31 Demo Day",
    "hero.apply": "立即報名",
    "registration.deadline.open": "報名截止",
    "registration.deadline.closed": "報名已截止",
    "registration.deadline.timezone": "台灣時間",
    "registration.closed.title": "報名已截止",
    "registration.closed.body": "報名於 8/5（三）23:59 結束，感謝所有報名的隊伍。",
    "registration.closed.result": "初選名單將於 8/7（五）以 Email 通知。",
    "countdown.beforeOpen": "距離開放報名",
    "countdown.beforeClose": "距離報名截止",
    "countdown.demoDay": "距離 Demo Day",
    "countdown.days": "天",
    "countdown.hours": "時",
    "countdown.minutes": "分",
    "countdown.seconds": "秒",
    "statband.prize": "總獎金・將隨贊助加碼",
    "statband.teams": "最多錄取隊伍",
    "statband.days": "天：兩日實作＋Demo Day",
    "statband.participants": "預計參賽者",
    "marquee.roles": "AI 工程師・資安研究員・區塊鏈開發者・產品經理・設計師・學生團隊・新創團隊・領域專家",
    "hero.venue": "N24 台北方舟",
    "hero.format": "兩日黑客松＋第三日 Demo Day",
    "rules.download": "比賽辦法 PDF",
    "rules.addendum": "規則補充說明",
    "why.title": "為什麼是現在",
    "why.subtitle": "AI Agent 開始行動了。信任還沒跟上。",
    "why.body": "當 Agent 代表人查詢、下單、送件或簽署時，關鍵不只是答案正確，而是能否說清楚誰授權、做了什麼、何時失效，以及事後如何追溯。",
    "why.q1": "它代表誰？",
    "why.q2": "被授權做什麼？",
    "why.q3": "授權何時失效？",
    "why.q4": "哪些動作需人類確認？",
    "why.q5": "出事後如何追溯？",
    "prize.title": "獎項",
    "prize.total": "總獎金 USD 14,000+",
    "prize.total.note": "將隨贊助加碼",
    "prize.body": "特別獎隊數與分配方式以正式公告為準。",
    "prize.grand.title": "冠軍",
    "prize.grand.count": "1 隊",
    "prize.grand.amount": "USD 5,000",
    "prize.runner.title": "亞軍",
    "prize.runner.count": "2 隊・每隊",
    "prize.runner.amount": "USD 2,000",
    "prize.third.title": "季軍",
    "prize.third.count": "3 隊・每隊",
    "prize.third.amount": "USD 1,000",
    "prize.special.title": "特別獎",
    "prize.special.amount": "USD 2,000",
    "roadmap.title": "時間軸",
    "roadmap.body": "從報名到 Demo Day。",
    "date.registration": "7/8（三）",
    "timeline.registration": "開放報名",
    "date.info": "7/20（一）",
    "timeline.info": "線上說明會",
    "timeline.now": "現在",
    "date.deadline": "8/5（三）23:59",
    "timeline.deadline": "報名截止（GMT+8）",
    "date.finalists": "8/7（五）",
    "timeline.finalists": "公告初選名單",
    "date.confirm": "8/9（日）23:59",
    "timeline.confirm": "入選者以 Email 回覆確認",
    "date.workshop1": "8/15（六）14:00–16:00",
    "timeline.workshop1": "Workshop #1（線上，限入選）",
    "date.workshop2": "8/22（六）10:00–17:00",
    "timeline.workshop2": "Workshop #2（線下，限入選）",
    "date.hackathon1": "8/29（六）",
    "timeline.hackathon1": "Hackathon Day 1",
    "date.hackathon2": "8/30（日）",
    "timeline.hackathon2": "Hackathon Day 2",
    "date.demo": "8/31（一）",
    "timeline.demo": "Demo Day",
    "info.title": "活動資訊",
    "info.subtitle": "兩日實作。第三天上台。",
    "benefits.title": "為什麼參加",
    "benefits.subtitle": "免費參加。全力以赴。",
    "benefit.demo.title": "Demo Day 舞台",
    "benefit.demo.body": "向產業評審與與會者展示成果。",
    "benefit.mentor.title": "Mentor Office Hours",
    "benefit.mentor.body": "現場導師支援與開發指導。",
    "benefit.poc.title": "POC 對接",
    "benefit.poc.body": "作品與場景問題接軌後續合作討論。",
    "benefit.proof.title": "完賽證明",
    "benefit.proof.body": "完成交付與展示即獲完賽證明。",
    "benefit.meals.title": "餐食與過夜",
    "benefit.meals.body": "活動期間供餐，8/29 晚間可選擇過夜。",
    "benefit.team.title": "跨域隊友",
    "benefit.team.body": "尚未組隊者可在賽前工作坊認識 AI、資安、區塊鏈與產品等跨域夥伴。",
    "position.title": "活動定位",
    "position.build.title": "兩日實作",
    "position.build.body": "入選者完成組隊後，現場完成可信 AI Agent 原型與 Demo Day 展示。",
    "position.memo.title": "治理／信任設計說明",
    "position.memo.body": "以一頁 Governance Gap Memo 說明作品的信任設計。",
    "position.poc.title": "週末實作到 POC",
    "position.poc.body": "把場景痛點、Agent 原型與後續合作可能性接起來。",
    "stat.teams.count": "最多 20",
    "stat.teams": "錄取隊伍",
    "stat.members": "每隊人數",
    "stat.participants": "預計參賽者",
    "stat.tracks": "產業命題",
    "stat.workshops": "賽前工作坊",
    "day1.title": "開幕與隊伍確認",
    "day1.body": "報到、活動規則說明、隊伍與命題開發方向確認。",
    "day2.title": "實作與交件",
    "day2.body": "Build sprint、mentor office hours、收尾與正式交件。",
    "day3.title": "成果簡報與頒獎",
    "day3.body": "成果簡報、評審、頒獎與完賽證明。",
    "tracks.title": "產業命題預告",
    "tracks.body": "六道產業命題預告已全數公開。完整命題內容於入選後工作坊公布。",
    "tracks.body.complete": "六道產業命題預告已全數公開。完整命題內容於入選後工作坊公布。",
    "tracks.note": "完整命題（背景、核心可信問題、方向提示）將於入選後工作坊公布，屆時亦說明命題選擇方式。命題 06 為 Track 01 延伸的加分題，可與其他命題同時挑戰。",
    "challenge.locked.title": "題目即將公布",
    "challenge.locked.date": "{date} 揭曉題名與題目摘要",
    "challenge.01.track": "Track 01｜供應鏈與貿易金融",
    "challenge.01.title": "製造貿易：碳足跡與 DPP 的資料流控制",
    "challenge.01.question": "碳足跡資料散落在內部系統與供應商之間；如何讓跨組織查驗成立，同時只揭露必要數據、不外洩製程機密？",
    "challenge.02.track": "Track 02｜電商與第三方支付",
    "challenge.02.title": "電支金融：隱私保護下的可疑行為偵測",
    "challenge.02.question": "開戶 KYC 已經扎實，但盜用與人頭帳戶往往發生在開戶後；如何持續辨識異常，又不攤開完整交易明細？",
    "challenge.03.track": "Track 03｜醫療保險",
    "challenge.03.title": "醫療保險：跨產業資料合作的誘因與邊界",
    "challenge.03.question": "醫院與保險公司的個資及法遵邏輯不同；如何只交換理賠所需的最小必要資訊，同時建立雙方願意合作的機制？",
    "challenge.04.track": "Track 04｜政府服務",
    "challenge.04.title": "政府服務：解決憑證碎片化背後的資料孤島",
    "challenge.04.question": "當 Agent 代辦跨機關申請時，如何讓既有憑證安全流動，並清楚劃分「代查」、「代送件」與本人確認的授權邊界？",
    "challenge.05.track": "Track 05｜普惠金融",
    "challenge.05.title": "移工數位信任：普惠金融與防詐的憑證機制",
    "challenge.05.question": "逾 87 萬移工面臨開戶障礙，也容易遭冒名利用；如何建立一套「能被信任、又不被冒用」的數位身分與憑證機制？",
    "challenge.06.track": "Track 01 延伸｜供應鏈與貿易金融",
    "challenge.06.title": "RBA 供應鏈合規的可驗證憑證機制",
    "challenge.06.question": "RBA 稽核仍高度依賴人工與紙本；如何讓供應鏈合規證明持續可驗證，同時不必揭露工廠的完整內部資料？",
    "challenge.06.badge": "加分題",
    "challenge.06.note": "加分題：可與 01–05 其中一題同時挑戰，作為加分項目。",
    "rules.title": "參賽資格",
    "rules.body": "個人或隊伍皆可先報名；最終以 3–5 人隊伍參賽，細節以正式簡章為準。",
    "rules.contact.line": "報名由 Team Leader 代表提交，個人亦可報名｜聯絡：",
    "apply.check1": "個人、未滿員隊伍或完整 3–5 人隊伍皆可報名",
    "apply.check2": "隊伍由 Team Leader 提交；個人由本人提交",
    "apply.check3": "自訂痛點與解法構想已想好一句話",
    "matchmaking.cta": "尋找隊友／團隊媒合",
    "back.top": "回到頂部",
    "finalists.title": "入選名單",
    "finalists.subtitle": "入選者與隊伍將於 8/7 公告。",
    "finalists.track.supply": "供應鏈",
    "finalists.track.ecommerce": "支付",
    "finalists.track.health": "醫療",
    "finalists.track.gov": "政府",
    "phase.screening": "初選名單 8/7 公告",
    "phase.demoday": "8/31 Demo Day",
    "phase.post": "活動已圓滿結束",
    "rules.audience": "參賽對象",
    "rules.a1": "學生、青年開發者、業界開發者。",
    "rules.a2": "AI／資料、資安、區塊鏈、產品、設計或專案管理人才。",
    "rules.a3": "供應鏈、支付、醫療保險、政府服務等領域參與者。",
    "rules.a4": "個人、未滿員隊伍或完整 3–5 人隊伍皆可報名；尚未完成組隊者可先提交，並於賽前工作坊媒合隊友，最終組成 3–5 人隊伍參賽。",
    "rules.a5": "報名時須年滿 18 歲。",
    "rules.team": "隊伍與出席",
    "rules.t1": "最終每隊 3–5 人，每位參賽者限加入一隊；報名時不要求已完成組隊。",
    "rules.delivery": "出席與交付",
    "rules.d0": "Team Leader（團隊代表）須全程參與所有指定流程。",
    "rules.d1": "兩場賽前工作坊限入選者參與，不開放旁聽。Team Leader 須全程出席兩場工作坊；其他隊員不強制，但強烈建議參與。尚未完成組隊者請參與工作坊媒合，以便確認最終隊伍。",
    "rules.d2": "Demo Day 由 Team Leader 或指定隊員簡報；得獎隊伍須最終名單之全體成員出席 Demo Day，方可領獎。",
    "rules.d3": "須完成程式碼儲存庫連結、Demo Day 簡報檔、Demo 連結或展示影片、一頁治理／信任設計說明（Governance Gap Memo）、README。",
    "rules.safety": "安全與資料",
    "rules.s1": "僅使用具合法授權的模型、資料、工具及第三方服務。",
    "rules.s2": "真實醫療、金融、政府或其他敏感資料不得使用。",
    "rules.s3": "敏感場景應使用匿名、合成或測試資料。",
    "rules.s4": "智慧財產權、影像授權、獎金稅務與活動規範以正式簡章為準。",
    "judging.title": "評分重點",
    "judging.body": "先書審。Demo Day 見真章。",
    "judging.prelim": "初選評估",
    "judging.relevance": "題目相關性",
    "judging.feasibility": "可行性",
    "judging.team": "團隊能力",
    "judging.finalTitle": "決選（Demo Day）",
    "judging.fit": "產業應用場景契合度",
    "judging.trust": "可信技術導入 AI Agent 的可行性",
    "judging.execution": "簡報與 Demo 呈現",
    "judging.insight": "問題洞察與創意巧思",
    "foundation.title": "信任要點",
    "foundation.body": "作品不必做到產品級；重點是讓評審看懂 Agent 代表誰、被允許做什麼、高風險動作是否受控，以及行為是否可追溯、授權是否可撤銷。",
    "foundation.core.title": "建議展示的 6 個信任要點",
    "foundation.group.note": "這 6 個要點是協助說明可信設計的參考面向；治理／信任設計說明（Governance Gap Memo）為正式交件項目。",
    "foundation.principal": "代表誰？Agent 代表哪一個人、團隊、法人或公部門單位。",
    "foundation.authorization": "被授權做什麼？誰授權、允許做什麼、禁止做什麼。",
    "foundation.tool": "能呼叫什麼工具？每個工具需要哪些權限與邊界。",
    "foundation.policy": "高風險動作如何被擋？付款、送件、簽署或讀取敏感資料需明確把關。",
    "foundation.audit": "如何追溯行動？記錄 Agent 的行動、決策與授權依據。",
    "foundation.expiry": "何時失效或撤銷？授權過期或撤銷後，Agent 必須停止執行。",
    "foundation.governance.title": "治理／信任設計說明",
    "foundation.governance": "以一頁治理／信任設計說明（Governance Gap Memo），說明作品如何回應這些信任要點。",
    "pre.events.title": "賽前活動",
    "pre.events.subtitle": "從活動說明、組隊媒合，到題目收斂。",
    "preevent.info.meta": "7/20（一）",
    "preevent.info.title": "線上說明會",
    "preevent.info.body": "開放所有人參加。於 Luma 完成報名後，會議連結將寄送至你的信箱；當天將說明活動內容並進行現場 Q&A。活動錄影不對外公開。",
    "preevent.info.body.past": "已於 7/20（一）舉行。當天說明活動內容並進行現場 Q&A；活動錄影不對外公開。",
    "preevent.info.badge.past": "已結束",
    "infoSession.banner": "線上說明會｜7/20（一）舉行・開放報名｜於 Luma 報名後寄送會議連結",
    "infoSession.register": "前往 Luma 報名說明會",
    "announce.cta": "前往 Luma 報名 →",
    "workshops.title": "賽前活動",
    "workshops.body": "兩場工作坊皆提供組隊媒合協助，限入選者參與；各項安排以主辦方最新公告為準。",
    "workshops.card1.meta": "8/15（六）14:00–16:00",
    "workshops.card1.title": "Workshop #1（線上）",
    "workshops.card1.body": "可信 AI Agent 與數位憑證工具導覽；尚未完成組隊者可在本場開始認識隊友與媒合。限入選者參加。",
    "workshops.card2.meta": "8/22（六）10:00–17:00",
    "workshops.card2.title": "Workshop #2（線下）",
    "workshops.card2.body": "六題完整命題公布、產業痛點說明與 POC 題目收斂；尚未完成組隊者可在本場持續媒合並確認最終隊伍。限入選者參加。",
    "judges.title": "陣容與夥伴陸續公告",
    "judges.subtitle": "評審、導師與各合作單位資訊將依正式確認進度更新。",
    "judges.group": "評審與導師",
    "judges.pending": "將邀請產業、學界與社群代表參與評審與指導；名單以正式公告為準。",
    "judges.organizer": "主辦單位",
    "judges.partners": "合作夥伴",
    "judges.sponsors": "贊助夥伴",
    "judges.toBeAnnounced": "待公開",
    "judges.organizer.name": "臺灣區塊鏈愛好者協會（TABEI）",
    "faq.title": "常見問答",
    "faq.body": "單人報名、組隊媒合、出席與交件，一次說清楚。",
    "venue.title": "場地與交通",
    "venue.subtitle": "N24 台北方舟。三天都在這。",
    "venue.name": "N24 台北方舟",
    "venue.pending": "地址：台北市南港區市民大道七段100號。交通：台鐵／捷運松山站步行約 5 分鐘；捷運後山埤站 4 號出口步行約 8 分鐘。",
    "venue.map": "在 Google 地圖開啟 ↗",
    "footer.newsletter": "訂閱協會電子報",
    "footer.follow": "追蹤臺灣區塊鏈愛好者協會",
    "footer.website": "回到 chain.tw",
    "footer.contact": "聯絡信箱：",
    "footer.org.zh": "臺灣區塊鏈愛好者協會",
    "footer.org.en": "Taiwan Association for Blockchain Ecosystem Innovation (TABEI)"
  },
  en: {
    "skip.main": "Skip to main content",
    "nav.menu": "Open menu",
    "nav.close": "Close menu",
    "aria.nav": "Main navigation",
    "aria.language": "Language selector",
    "aria.registrationFlow": "Registration and team-matching process",
    "aria.eventInfo": "Event information",
    "aria.eventNumbers": "Event highlights",
    "aria.roles": "Who should join",
    "aria.timeline": "Event timeline",
    "aria.eventScale": "Event scale",
    "aria.organizerVenue": "Organizer and venue",
    "aria.mapTitle": "Google Map for N24 Taipei Ark",
    "nav.format": "Schedule",
    "nav.tracks": "Challenges",
    "nav.rules": "Rules",
    "nav.prizes": "Prizes",
    "nav.faq": "FAQ",
    "meta.title": "Trustworthy AI Hackathon 2026 | TABEI",
    "meta.description": "Trustworthy AI Hackathon takes place Aug 29–31, 2026 at N24 Taipei Ark, focusing on identity, authorization, action boundaries, and traceability for trustworthy AI Agents.",
    "og.title": "Trustworthy AI Hackathon",
    "hero.title": "Trustworthy AI Hackathon",
    "solo.badge": "Solo or incomplete teams welcome",
    "solo.title": "Apply solo or with an incomplete team",
    "solo.body": "Apply solo, with an incomplete team, or as a full team of 3–5. Selected participants can match at both pre-event workshops and form a final team of 3–5.",
    "solo.step1.title": "Submit your application",
    "solo.step1.body": "Apply for yourself; teams apply through a Team Leader.",
    "solo.step2.title": "Meet and match with teammates",
    "solo.step2.body": "Use the matching board; both workshops support matching if selected.",
    "solo.step3.title": "Confirm a team of 3–5",
    "solo.step3.body": "Final teams have 3–5 members; each participant may join one team.",
    "hero.body": "When AI Agents start acting for people or organizations, identity, authorization, action boundaries and traceability must be designed clearly.",
    "hero.date": "08.29-08.30 Hackathon | 08.31 Demo Day",
    "hero.apply": "Apply Now",
    "registration.deadline.open": "Apply by",
    "registration.deadline.closed": "Applications closed",
    "registration.deadline.timezone": "UTC+8",
    "registration.closed.title": "Registration Closed",
    "registration.closed.body": "Registration closed on Aug 5 at 23:59 (GMT+8). Thank you to all who applied.",
    "registration.closed.result": "Shortlist results will be sent by email on Aug 7.",
    "countdown.beforeOpen": "Applications open in",
    "countdown.beforeClose": "Applications close in",
    "countdown.demoDay": "Demo Day in",
    "countdown.days": "Days",
    "countdown.hours": "Hrs",
    "countdown.minutes": "Min",
    "countdown.seconds": "Sec",
    "statband.prize": "Total prize · grows with sponsors",
    "statband.teams": "Teams selected (max)",
    "statband.days": "Days · 2 build + Demo Day",
    "statband.participants": "Expected participants",
    "marquee.roles": "AI Engineers · Security Researchers · Blockchain Devs · Product Managers · Designers · Student Teams · Startups · Domain Experts",
    "hero.venue": "N24 Taipei Ark",
    "hero.format": "2-day hackathon + Demo Day",
    "rules.download": "Rules PDF",
    "rules.addendum": "Rules Addendum",
    "why.title": "Why Now",
    "why.subtitle": "AI Agents are acting. Trust hasn't caught up.",
    "why.body": "When Agents query, order, file or sign on someone's behalf, the key question is not only whether the answer is correct, but who authorized the action, what happened, when authorization expires and how it can be traced.",
    "why.q1": "Who does it represent?",
    "why.q2": "What is it authorized to do?",
    "why.q3": "When does authorization expire?",
    "why.q4": "Which actions require human approval?",
    "why.q5": "How can incidents be traced?",
    "prize.title": "Prizes",
    "prize.total": "Total Prize Pool USD 14,000+",
    "prize.total.note": "May increase with sponsorship",
    "prize.body": "The number of Special Award recipients and allocation method are subject to official announcement.",
    "prize.grand.title": "Champion",
    "prize.grand.count": "1 team",
    "prize.grand.amount": "USD 5,000",
    "prize.runner.title": "Runner-up",
    "prize.runner.count": "2 teams · each",
    "prize.runner.amount": "USD 2,000",
    "prize.third.title": "Third Place",
    "prize.third.count": "3 teams · each",
    "prize.third.amount": "USD 1,000",
    "prize.special.title": "Special Award",
    "prize.special.amount": "USD 2,000",
    "roadmap.title": "Roadmap",
    "roadmap.body": "From sign-up to Demo Day.",
    "date.registration": "Jul 8 (Wed)",
    "timeline.registration": "Applications open",
    "date.info": "Jul 20 (Mon)",
    "timeline.info": "Online info session",
    "timeline.now": "Now",
    "date.deadline": "Aug 5 (Wed) 23:59",
    "timeline.deadline": "Application deadline (GMT+8)",
    "date.finalists": "Aug 7 (Fri)",
    "timeline.finalists": "Finalists announced",
    "date.confirm": "Aug 9 (Sun) 23:59",
    "timeline.confirm": "Selected participants confirm by email",
    "date.workshop1": "Aug 15 (Sat) 14:00–16:00",
    "timeline.workshop1": "Workshop #1 (online, finalists only)",
    "date.workshop2": "Aug 22 (Sat) 10:00–17:00",
    "timeline.workshop2": "Workshop #2 (in-person, finalists only)",
    "date.hackathon1": "Aug 29 (Sat)",
    "timeline.hackathon1": "Hackathon Day 1",
    "date.hackathon2": "Aug 30 (Sun)",
    "timeline.hackathon2": "Hackathon Day 2",
    "date.demo": "Aug 31 (Mon)",
    "timeline.demo": "Demo Day",
    "info.title": "Event Info",
    "info.subtitle": "Two days to build. One day to show.",
    "benefits.title": "Why Join",
    "benefits.subtitle": "Free to join. Built to push you.",
    "benefit.demo.title": "Demo Day stage",
    "benefit.demo.body": "Present your build to industry judges and attendees.",
    "benefit.mentor.title": "Mentor office hours",
    "benefit.mentor.body": "On-site mentor support and build guidance.",
    "benefit.poc.title": "POC matchmaking",
    "benefit.poc.body": "Connect your work to scenario problems and follow-on collaboration.",
    "benefit.proof.title": "Completion proof",
    "benefit.proof.body": "Finish delivery and demo to earn a completion proof.",
    "benefit.meals.title": "Meals & overnight",
    "benefit.meals.body": "Meals are provided during the event; an optional overnight stay is available on the night of Aug 29.",
    "benefit.team.title": "Cross-domain teammates",
    "benefit.team.body": "Participants without a team can meet cross-domain peers in AI, security, blockchain, product and more at the pre-event workshops.",
    "position.title": "What It Is",
    "position.build.title": "2-day build",
    "position.build.body": "After finalizing teams, selected participants build a trustworthy AI Agent prototype and Demo Day presentation on site.",
    "position.memo.title": "Governance / Trust Design Note",
    "position.memo.body": "A one-page Governance Gap Memo explains the project's trust design.",
    "position.poc.title": "Weekend build toward POC",
    "position.poc.body": "Connect scenario problems, Agent prototypes and follow-on collaboration opportunities.",
    "stat.teams.count": "Up to 20",
    "stat.teams": "selected teams",
    "stat.members": "members per team",
    "stat.participants": "expected participants",
    "stat.tracks": "Challenge Topics",
    "stat.workshops": "workshops",
    "day1.title": "Kickoff and team confirmation",
    "day1.body": "Check-in, rules briefing, plus team and challenge-development direction confirmation.",
    "day2.title": "Build and submit",
    "day2.body": "Build sprint, mentor office hours, finalization and formal submission.",
    "day3.title": "Demos and awards",
    "day3.body": "Demos, judging, awards and completion proof.",
    "tracks.title": "Challenge Topics Preview",
    "tracks.body": "All six challenge previews are now available. Full briefs will be released at the post-selection workshops.",
    "tracks.body.complete": "All six challenge previews are now available. Full briefs will be released at the post-selection workshops.",
    "tracks.note": "The full briefs (background, core trust questions, and direction prompts) will be revealed at the post-selection workshops, where the topic-selection process will also be explained. Topic 06 extends Track 01 as a bonus challenge and may be attempted alongside another topic.",
    "challenge.locked.title": "Challenge coming soon",
    "challenge.locked.date": "Title and challenge summary revealed on {date}",
    "challenge.01.track": "Track 01 | Supply Chain & Trade Finance",
    "challenge.01.title": "Manufacturing & Trade: Data-Flow Control for Carbon Footprints and DPP",
    "challenge.01.question": "Carbon-footprint data is scattered across internal systems and suppliers. How can it be verified across organizations while revealing only what is necessary and protecting confidential production processes?",
    "challenge.02.track": "Track 02 | E-commerce & Third-Party Payments",
    "challenge.02.title": "Electronic Payments & Finance: Privacy-Preserving Suspicious-Behavior Detection",
    "challenge.02.question": "KYC at onboarding is already robust, but account theft and mule-account activity often emerge later. How can anomalies be detected continuously without exposing complete transaction details?",
    "challenge.03.track": "Track 03 | Healthcare & Insurance",
    "challenge.03.title": "Healthcare & Insurance: Incentives and Boundaries for Cross-Industry Data Collaboration",
    "challenge.03.question": "Healthcare providers and insurers follow different privacy and compliance models. How can they exchange only the minimum information needed for claims while creating incentives for both sides to collaborate?",
    "challenge.04.track": "Track 04 | Government Services",
    "challenge.04.title": "Government Services: Breaking Down Data Silos Behind Credential Fragmentation",
    "challenge.04.question": "When an Agent handles a cross-agency application, how can existing credentials move safely while keeping clear authorization boundaries between checking, submitting, and personal confirmation?",
    "challenge.05.track": "Track 05 | Financial Inclusion",
    "challenge.05.title": "Migrant Digital Trust: Credential Mechanisms for Financial Inclusion and Fraud Prevention",
    "challenge.05.question": "Over 870,000 migrant workers face barriers to opening accounts and are vulnerable to identity misuse. How can digital identity and credentials make a person trusted without making their identity easy to exploit?",
    "challenge.06.track": "Track 01 Extension | Supply Chain & Trade Finance",
    "challenge.06.title": "Verifiable Credentials for RBA Supply-Chain Compliance",
    "challenge.06.question": "RBA audits still rely heavily on manual reviews and paper records. How can compliance evidence remain continuously verifiable without exposing a factory's complete internal data?",
    "challenge.06.badge": "Bonus",
    "challenge.06.note": "Bonus challenge: may be attempted alongside one of Topics 01–05 for additional credit.",
    "rules.title": "Eligibility",
    "rules.body": "Apply solo or as a team; final teams are 3–5 people. See the official rules for full details.",
    "rules.contact.line": "Submitted by the Team Leader, or register solo | Contact: ",
    "apply.check1": "Solo, incomplete, or full teams of 3–5 may apply",
    "apply.check2": "Teams submit via a Team Leader; solo applicants submit for themselves",
    "apply.check3": "One-line pain point and solution concept ready",
    "matchmaking.cta": "Find Teammates",
    "back.top": "Back to top",
    "finalists.title": "Selected Participants & Teams",
    "finalists.subtitle": "The selected list will be announced on Aug 7.",
    "finalists.track.supply": "Supply",
    "finalists.track.ecommerce": "Payments",
    "finalists.track.health": "Health",
    "finalists.track.gov": "Gov",
    "phase.screening": "Finalists announced Aug 7",
    "phase.demoday": "Demo Day · Aug 31",
    "phase.post": "Event concluded",
    "rules.audience": "Who can participate",
    "rules.a1": "Students, young developers and industry developers.",
    "rules.a2": "AI / data, security, blockchain, product, design or project-management talent.",
    "rules.a3": "Participants from supply chain, payments, health insurance and government services.",
    "rules.a4": "Solo applicants, incomplete teams, and full teams of 3–5 may register. Participants who still need teammates can apply first and match at the pre-event workshops, then compete in a final team of 3–5.",
    "rules.a5": "Participants must be 18 or older at registration.",
    "rules.team": "Team and attendance",
    "rules.t1": "Final teams are 3–5 people and each participant may join only one team; you do not need a complete team when applying.",
    "rules.delivery": "Attendance and deliverables",
    "rules.d0": "The Team Leader must participate throughout all required program steps.",
    "rules.d1": "The two pre-event workshops are for selected participants only and are not open to auditing. The Team Leader must attend both workshops throughout; other members are not required, but are strongly encouraged to join. Participants who still need teammates should attend the matching sessions to confirm a final team.",
    "rules.d2": "On Demo Day, the Team Leader or a designated member presents. Winning teams must have every member on the final roster attend Demo Day to receive prizes.",
    "rules.d3": "Teams must submit a code repository link, Demo Day slide deck, demo link or showcase video, one-page governance / trust design note (Governance Gap Memo), and README.",
    "rules.safety": "Safety and data",
    "rules.s1": "Use only legally authorized models, data, tools and third-party services.",
    "rules.s2": "Do not use real medical, financial, government or other sensitive data.",
    "rules.s3": "Sensitive scenarios should use anonymized, synthetic or test data.",
    "rules.s4": "IP, media consent, prize tax and event logistics are subject to the official rules.",
    "judging.title": "Judging & Trust Points",
    "judging.body": "Written review first. Demo Day decides.",
    "judging.prelim": "Preliminary review",
    "judging.relevance": "Relevance",
    "judging.feasibility": "Feasibility",
    "judging.team": "Team capability",
    "judging.finalTitle": "Final Judging (Demo Day)",
    "judging.fit": "Industry scenario fit",
    "judging.trust": "Feasibility of a trustworthy AI Agent",
    "judging.execution": "Presentation & demo",
    "judging.insight": "Insight & creativity",
    "foundation.title": "Trust Points",
    "foundation.body": "Projects do not need to be product-grade. The focus is whether judges can understand who the Agent represents, what it is allowed to do, whether high-risk actions are controlled, and whether behavior is traceable and authorization can be revoked.",
    "foundation.core.title": "Six suggested trust points",
    "foundation.group.note": "These six points are reference angles for explaining trustworthy design; the governance / trust design note (Governance Gap Memo) is a required deliverable.",
    "foundation.principal": "Who is represented? Which person, team, legal entity or public-sector unit does the Agent represent?",
    "foundation.authorization": "What is authorized? Who authorizes it, what is allowed and what is forbidden?",
    "foundation.tool": "What tools can it call? What permissions and boundaries does each tool require?",
    "foundation.policy": "How are high-risk actions blocked? Payments, filing, signing or reading sensitive data require explicit gates.",
    "foundation.audit": "How are actions traced? Record the Agent's actions, decisions and authorization basis.",
    "foundation.expiry": "When does it expire or get revoked? After expiry or revocation, the Agent must stop executing.",
    "foundation.governance.title": "Governance / Trust Design Note",
    "foundation.governance": "Use a one-page governance / trust design note (Governance Gap Memo) to explain how the project responds to these trust points.",
    "pre.events.title": "Pre-event Activities",
    "pre.events.subtitle": "From event briefing and team matching to project scoping.",
    "preevent.info.meta": "Jul 20 (Mon)",
    "preevent.info.title": "Online info session",
    "preevent.info.body": "Open to everyone. RSVP on Luma and the meeting link will be emailed to you. The session will include an event overview and live Q&A. The recording will not be made public.",
    "preevent.info.body.past": "Held on July 20 (Mon). The session covered the event overview and live Q&A. The recording is not publicly released.",
    "preevent.info.badge.past": "Concluded",
    "infoSession.banner": "Online info session | Jul 20 (Mon) · Open to all — RSVP on Luma to get the link",
    "infoSession.register": "RSVP on Luma",
    "announce.cta": "RSVP on Luma →",
    "workshops.title": "Pre-event Activities",
    "workshops.body": "Both workshops provide team-matching support and are for selected participants only; arrangements are subject to the organizer's latest announcement.",
    "workshops.card1.meta": "Aug 15 (Sat) 14:00–16:00",
    "workshops.card1.title": "Workshop #1 (Online)",
    "workshops.card1.body": "A tour of trustworthy AI-Agent and digital credential tooling; participants who still need teammates can start meeting and matching here. Open to selected participants only.",
    "workshops.card2.meta": "Aug 22 (Sat) 10:00–17:00",
    "workshops.card2.title": "Workshop #2 (In-person)",
    "workshops.card2.body": "Release of the six full challenge briefs, industry pain-point briefing, and POC topic scoping; participants who still need teammates can continue matching and confirm their final team here. Open to selected participants only.",
    "judges.title": "Lineup & Partners",
    "judges.subtitle": "Judges, mentors and participating organizations will be announced as confirmations are finalized.",
    "judges.group": "Judges & mentors",
    "judges.pending": "Industry, academic and community representatives will be invited for judging and mentorship; names are subject to official announcement.",
    "judges.organizer": "Organizer",
    "judges.partners": "Partners",
    "judges.sponsors": "Sponsoring Partners",
    "judges.toBeAnnounced": "To be announced",
    "judges.organizer.name": "Taiwan Association for Blockchain Ecosystem Innovation (TABEI)",
    "faq.title": "FAQ",
    "faq.body": "Solo registration, team matching, attendance and deliverables — explained in one place.",
    "venue.title": "Venue & Access",
    "venue.subtitle": "N24 Taipei Ark. All three days.",
    "venue.name": "N24 Taipei Ark",
    "venue.pending": "Address: No. 100, Sec. 7, Civic Blvd., Nangang Dist., Taipei City. Access: about a 5-minute walk from TRA / MRT Songshan Station, or about an 8-minute walk from MRT Houshanpi Station Exit 4.",
    "venue.map": "Open in Google Maps ↗",
    "footer.newsletter": "Subscribe to TABEI newsletter",
    "footer.follow": "Follow TABEI",
    "footer.website": "Back to chain.tw",
    "footer.contact": "Contact: ",
    "footer.org.zh": "Taiwan Association for Blockchain Ecosystem Innovation",
    "footer.org.en": "Taiwan Association for Blockchain Ecosystem Innovation (TABEI)"
  }
};

// Add confirmed judges and mentors here as they are announced.
// Each field may provide localized values; image is an optional asset path.
window.JUDGES = [
  // {
  //   name: { "zh-Hant": "", en: "" },
  //   role: { "zh-Hant": "", en: "" },
  //   organization: { "zh-Hant": "", en: "" },
  //   image: ""
  // }
];

window.FAQ_GROUPS = {
  "zh-Hant": [
    ["A. 報名與資格", [
      ["這場活動是免費的嗎？", "完全免費。線下工作坊與活動期間提供餐食。"],
      ["誰可以參加？", "年滿 18 歲，對 AI、軟體開發、設計、產品、資安、數位身份或相關領域有興趣之學生、社會人士與業界人士。"],
      ["有年齡限制嗎？", "有，本活動限年滿 18 歲（報名時全體成員均須年滿 18 歲）。"],
      ["每隊幾人？", "最終每隊 3–5 人，每位參賽者僅能加入一隊；報名時不要求已完成組隊，個人或未滿員隊伍也能先提交。"],
      ["可以個人報名嗎？", "可以。個人、未滿員隊伍與完整 3–5 人隊伍都能報名；個人報名者由本人填寫報名表並作為聯絡窗口。若入選，須在活動前完成 3–5 人隊伍。"],
      ["個人報名後，如何完成組隊？", "報名後可先在<a href=\"https://padlet.com/Trustworthy/trustworthy-ai-hackathon-6r3tvsp4rktkz5xy\" target=\"_blank\" rel=\"noopener noreferrer\" data-matchmaking-link>團隊媒合平台</a>介紹專長與尋找夥伴。若入選，兩場賽前工作坊都會提供媒合協助；建議個人與未滿員隊伍參與，以便認識隊友、討論分工，並確認最終 3–5 人名單。"],
      ["入選後可以增加原本沒報名的成員嗎？", "可以。最終每隊 3–5 人，每位參賽者限加入一隊；成員異動請於 8/22 前以 Email 通知主辦方（hackathon2026@chain.tw），以利確認最終名單、餐食與完賽證明。賽前工作坊仍限入選者參加。"],
      ["怎麼報名？", "於報名期間填寫線上報名表：7/8 開放、8/5 23:59 截止（GMT+8），由 Team Leader（團隊代表）代表提交，每隊僅提交一次；個人報名者以本人為聯絡窗口。"],
      ["報名要準備什麼？", "團隊背景（建議整理為一份 PDF：成員與角色分工、所屬單位、相關經驗）、想解決的痛點、初步解法構想，以及 GitHub 或作品連結（選填）。個人報名者，團隊背景可改填個人背景與專長。報名所提痛點用於書審評估；入選後將依公布之命題進行開發。"]
    ]],
    ["B. 主題與技術", [
      ["有指定題目或賽道嗎？", "正式題目由主辦方與產業夥伴共同命題，共六大真實場景（見主題區預告）；完整命題於入選後的工作坊公布，並說明命題選擇方式。報名時請提出你們自訂的痛點與解法構想，作為書面初審的評估依據。其中命題 06 為加分題，團隊可於主要命題之外同時挑戰。"],
      ["技術或框架有限制嗎？", "技術自由，但作品須能展示可信 AI Agent 的身份、授權、行動邊界、稽核與撤銷思考，且僅能使用合法授權之模型、資料與工具。"],
      ["可信 AI Agent 建議展示什麼？", "代表誰（Principal）、被授權做什麼（Authorization）、可呼叫的工具與動作（Tool / Action）、政策關卡（Policy Gate）、稽核軌跡（Audit Log）、失效與撤銷（Expiry / Revocation）。"],
      ["一定要用區塊鏈或數位憑證（VC）嗎？", "不強制。只要能清楚展示身份、授權、驗證、稽核與撤銷即可；區塊鏈／VC 是選項而非必需。"],
      ["需要自備設備嗎？", "請自備筆電及開發所需個人裝置；現場提供網路、電力與活動期間餐食。"]
    ]],
    ["C. 時程、出席與交件", [
      ["重要時程有哪些？", "7/8 開放報名、7/20 線上說明會、8/5 23:59 截止（GMT+8）、8/7 公告入選、8/9 23:59 入選者以 Email 回覆確認、8/15 14:00–16:00 工作坊 #1（線上）、8/22 10:00–17:00 工作坊 #2（線下）、8/29-8/30 Hackathon、8/31 Demo Day。"],
      ["Team Leader 一定要出席嗎？", "是。Team Leader 須全程出席兩場賽前工作坊、Hackathon 與 Demo Day。線上說明會已於 7/20 舉行，活動錄影不對外公開。"],
      ["其他隊員一定要參加工作坊嗎？", "已完成組隊者除 Team Leader 須全程出席外，其他隊員不強制，但強烈建議參與。個人或未滿員隊伍若需要媒合，請參與賽前工作坊，以便認識隊友並確認最終隊伍。"],
      ["有提供過夜嗎？", "8/29 晚間提供一晚過夜安排，自由參加；可選擇不過夜或當日往返。過夜名額、分區與相關安排將於錄取確認後另行通知。"],
      ["要交什麼？", "程式碼儲存庫（GitHub）、簡報、Demo 連結或影片、一頁治理／信任設計說明、README。"],
      ["交件截止什麼時候？", "8/30（日）23:59 前完成交件，缺件、逾期或無法展示可能影響評分、完賽或獲獎資格。"],
      ["Demo Day 怎麼進行？", "每隊約 5 分鐘成果簡報，並保留評審提問時間（實際秒數以現場公告為準）。Team Leader 須到場，簡報得由 TL 或其指定隊員擔任。最終名單之全體成員均須出席，得獎隊伍並以此為領獎條件。"]
    ]],
    ["D. 評分、獎項與法務", [
      ["怎麼評分？", "初選（書面）：題目相關性 50%、可行性 30%、團隊能力 20%。<br>決選（Demo Day）：產業應用場景契合度 35%、可信技術導入 AI Agent 的可行性 25%、簡報與 Demo 呈現 25%、問題洞察與創意巧思 15%。"],
      ["獎項有哪些？", "現金獎金池 USD 14,000+（將隨贊助加碼）：冠軍 1 隊 USD 5,000、亞軍 2 隊各 USD 2,000、季軍 3 隊各 USD 1,000、特別獎 USD 2,000。"],
      ["領獎有條件嗎？", "有。得獎隊伍須完成必要交件、於 Demo Day 完成展示，且最終名單之全體成員出席 Demo Day，方可領獎；未能全體到場者，主辦得保留、調整或取消該隊獎項。"],
      ["智慧財產權歸誰？", "作品智財原則上歸該隊。主辦與合作單位得為活動紀錄、成果發表與非商業宣傳，使用隊伍名稱、作品名稱、公開簡介、簡報與展示內容、現場照片及影片。"],
      ["個人資料怎麼處理？", "僅用於本活動之報名、審查、聯絡、活動營運、現場管理、證書／憑證發放、成果紀錄與必要行政用途，並依個人資料保護相關法令辦理；活動現場將攝錄影，並可能用於活動紀錄與宣傳。"],
      ["資料使用有什麼限制？", "僅能使用合法授權之模型、資料、API 與工具；不得使用未授權或真實敏感資料，敏感情境須以匿名、合成或測試資料替代。"],
      ["有問題找誰？", "聯絡窗口：hackathon2026@chain.tw"]
    ]]
  ],
  en: [
    ["A. Registration and Eligibility", [
      ["Is the event free?", "Yes. The event is completely free. Meals are provided during the in-person workshop and the event."],
      ["Who can join?", "Students, professionals, and industry practitioners aged 18 or older who are interested in AI, software development, design, product, cybersecurity, digital identity, or related fields."],
      ["Is there an age requirement?", "Yes. This event is limited to participants aged 18 or older; all team members must be 18 or older at registration."],
      ["How many members per team?", "Final teams are 3–5 people, and each participant may join only one team. You do not need a complete team when applying; solo applicants and incomplete teams may submit first."],
      ["Can I register as an individual?", "Yes. Solo applicants, incomplete teams, and full teams of 3–5 may register. Solo applicants complete the form themselves and serve as their own contact. If selected, they must join a final team of 3–5 before the event."],
      ["How do solo applicants complete a team?", "After applying, introduce your skills and look for teammates on the <a href=\"https://padlet.com/Trustworthy/trustworthy-ai-hackathon-6r3tvsp4rktkz5xy\" target=\"_blank\" rel=\"noopener noreferrer\" data-matchmaking-link>matching board</a>. If selected, team-matching support is available at both pre-event workshops. Solo applicants and incomplete teams are encouraged to attend so they can meet teammates, discuss roles, and confirm a final roster of 3–5."],
      ["Can we add members who did not originally register after selection?", "Yes. Final teams must have 3–5 members, and each participant may join only one team. Please notify the organizer by Email at hackathon2026@chain.tw of any roster changes by Aug 22 so the final roster, meals, and completion certificates can be confirmed. The pre-event workshops remain limited to selected participants."],
      ["How do I register?", "Complete the online registration form during the window: opens 7/8, closes 8/5 at 23:59 (GMT+8). The Team Leader submits on behalf of the team, once per team; solo registrants are their own contact."],
      ["What should we prepare for registration?", "Team background (suggested as one PDF: members, roles, organizations and relevant experience), the pain point you want to solve, initial solution idea, and optional GitHub or portfolio links. Solo registrants may describe their own background and skills instead of a team background. The pain point submitted at registration is used for written-review evaluation; selected participants will build according to the announced challenge briefs."]
    ]],
    ["B. Themes and Technology", [
      ["Are there assigned topics or tracks?", "The official challenges are co-developed by the organizer and industry partners and cover six real-world scenarios (see the preview in the Challenge Topics section). Full briefs will be revealed at the post-selection workshops, along with the topic-selection process. At registration, submit your own pain point and proposed solution as material for the preliminary written review. Topic 06 is a bonus challenge that teams may take on in addition to their main topic."],
      ["Any technology restrictions?", "Technology is open, but the project should demonstrate thinking around identity, authorization, action boundaries, auditability and revocation for a trustworthy AI Agent, using only legally licensed models, data and tools."],
      ["What should a trustworthy AI Agent show?", "Principal, Authorization, Tool / Action, Policy Gate, Audit Log, and Expiry / Revocation."],
      ["Do we have to use blockchain or verifiable credentials (VC)?", "No. Blockchain and VC are options, not requirements. The work only needs to clearly show identity, authorization, verification, auditability and revocation."],
      ["Do I need to bring my own equipment?", "Please bring your own laptop and personal devices needed for development. Network, power, and meals during the event are provided on-site."]
    ]],
    ["C. Schedule, Attendance, and Deliverables", [
      ["What are the key dates?", "7/8 applications open, 7/20 online info session, 8/5 at 23:59 (GMT+8) application deadline, 8/7 finalists announced, 8/9 at 23:59 selected participants confirm by email, 8/15 14:00–16:00 Workshop #1 (online), 8/22 10:00–17:00 Workshop #2 (in-person), 8/29-8/30 Hackathon, 8/31 Demo Day."],
      ["Does the Team Leader have to attend?", "Yes. The Team Leader must attend both pre-event workshops, the Hackathon, and Demo Day. The online info session was held on July 20. The recording is not publicly released."],
      ["Do all other members have to attend the workshops?", "For complete teams, only the Team Leader is required to attend throughout, though other members are strongly encouraged to join. Solo applicants and incomplete teams that need matching should attend the pre-event workshops to meet teammates and confirm their final team."],
      ["Is overnight stay available?", "A one-night stay is available on the night of Aug 29 and is optional. You may opt out or commute on the same day. Capacity, zoning, and related arrangements will be announced after finalist confirmation."],
      ["What do we submit?", "A GitHub repository, a slide deck, a demo link or video, a one-page governance / trust design note, and a README."],
      ["When is the submission deadline?", "By 23:59 on Sunday 8/30. Missing, late, or non-demoable submissions may affect scoring, completion, or prize eligibility."],
      ["How does Demo Day work?", "Each team gives an approximately 5-minute presentation, with time reserved for judges' Q&A. Exact timing is subject to on-site announcement. The Team Leader must be present; the presentation may be delivered by the TL or a designated team member. All members on the final roster must attend; for winning teams, this is also a condition for receiving the prize."]
    ]],
    ["D. Judging, Prizes, and Legal", [
      ["How is judging done?", "Preliminary review (written): topic relevance 50%, feasibility 30%, team capability 20%.<br>Final (Demo Day): industry scenario fit 35%, feasibility of a trustworthy AI Agent 25%, presentation & demo 25%, insight & creativity 15%."],
      ["What are the prizes?", "Cash prize pool of USD 14,000+ (may increase with sponsorship): Champion, 1 team at USD 5,000; Runner-up, 2 teams at USD 2,000 each; Third Place, 3 teams at USD 1,000 each; Special Award, USD 2,000."],
      ["Are there conditions for receiving prizes?", "Yes. Winning teams must complete required submissions, complete their Demo Day presentation, and have all final-roster members attend Demo Day to receive prizes. If not all members attend, the organizer may reserve, adjust, or cancel the team's prize."],
      ["Who owns the intellectual property?", "Project IP generally belongs to the team. The organizer and partners may use team names, project names, public summaries, slides, demo content, on-site photos, and videos for event documentation, outcome publication, and non-commercial promotion."],
      ["How is personal data handled?", "Personal data is used only for registration, review, contact, event operations, on-site management, certificate / credential issuance, outcome records, and necessary administration under data-protection law. The event will be filmed and may be used for documentation and promotion."],
      ["What are the data-use restrictions?", "Use only legally authorized models, data, APIs and tools. Do not use unauthorized or real sensitive data; sensitive scenarios must use anonymized, synthetic or test data."],
      ["Who do I contact?", "Contact: hackathon2026@chain.tw"]
    ]]
  ]
};
